### ISSUE TITLE
/.../orbit2sch.abi3.so: undefined symbol: orbit2sch_

### ISSUE THREAD

**Issue by alphanaltinok** [isce-framework/isce2#174]
/home/ops/ariamh/interferogram/sentinel/get_union_bbox.sh 
encounters "undefined symbol: orbit2sch_", any ideas?

Traceback (most recent call last):
  File "/home/ops/ariamh/interferogram/sentinel/create_standard_product_s1.py", line 1860, in 
    status = main()
  File "/home/ops/ariamh/interferogram/sentinel/create_standard_product_s1.py", line 1046, in main
    match_pol), shell=True)
  File "/opt/conda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/ops/ariamh/interferogram/sentinel/get_union_bbox.sh -o bbox.json *.SAFE/annotation/s1?-iw?-slc-vv-*.xml' returned non-zero exit status 1.

# ----- errors|exception found in log -----
ImportError: /opt/isce2/isce/components/stdproc/orbit/orbit2sch.abi3.so: undefined symbol: orbit2sch_
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/ops/ariamh/interferogram/sentinel/get_union_bbox.sh -o bbox.json *.SAFE/annotation/s1?-iw?-slc-vv-*.xml' returned non-zero exit status 1.

**Comment by rtburns-jpl** [comment]
AFAIR this issue was due to not having the Stanford code installed alongside ISCE2 – it’s required to use some modules, including orbit2sch. Let me know if this is resolved and I'll close.

**Comment by maltevoege** [comment]
I have the same issue as descibed in the post above, when using the prepSlcSensors.py script. Could you explain what the "Stanford code" is that should be installed alongside ISCE2 to solve this issue and point me to where I could get it?

**Comment by rtburns-jpl** [comment]
We weren't able to open source some parts of isce2 which are owned by Stanford. If you have a license, you may be able to download an older release containing the code from here: https://winsar.unavco.org/software/isce
