### ISSUE TITLE
rtcApp.py on isce/isce2 dockers fails with importerror since tag 20200726

### ISSUE THREAD

**Issue by vincentschut** [isce-framework/isce2#183]
I hope this is also the place to file issues with the docker images provided on docker hub (https://hub.docker.com/r/isce/isce2/tags); if not, please let me know.

The problem is that the image with tag 20200719 is the last one for which rtcApp.py works for me. All the later ones fail with an ImportError, caused by missing .so files:

```
Traceback (most recent call last):
  File "/opt/isce2/isce/applications/rtcApp.py", line 229, in <module>
    class GRDSAR(Application):
  File "/opt/isce2/isce/applications/rtcApp.py", line 423, in GRDSAR
    @use_api
  File "/opt/isce2/isce/components/isceobj/Util/decorators.py", line 282, in use_api
    from iscesys.ImageApi.DataAccessorPy import DataAccessor
  File "/opt/isce2/isce/components/iscesys/ImageApi/DataAccessorPy.py", line 31, in <module>
    from iscesys.ImageApi import DataAccessor as DA
ImportError: libhdf5.so.101: cannot open shared object file: No such file or directory

```
or (on 2.4.0):
```
Traceback (most recent call last):
  File "/opt/isce2/isce/applications/rtcApp.py", line 229, in <module>
    class GRDSAR(Application):
  File "/opt/isce2/isce/applications/rtcApp.py", line 423, in GRDSAR
    @use_api
  File "/opt/isce2/isce/components/isceobj/Util/decorators.py", line 282, in use_api
    from iscesys.ImageApi.DataAccessorPy import DataAccessor
  File "/opt/isce2/isce/components/iscesys/ImageApi/DataAccessorPy.py", line 31, in <module>
    from iscesys.ImageApi import DataAccessor as DA
ImportError: libgdal.so.20: cannot open shared object file: No such file or directory
```

**Comment by vincentschut** [comment]
Works again on 2.4.1. Closing.
