### ISSUE TITLE
stripmapStack incompatible with GDAL 3.1.2?

### ISSUE THREAD

**Issue by EJFielding** [isce-framework/isce2#194]
I recently built ISCE2 (with a git pull this week from the main branch) using an Anaconda3 environment. I note that it has GDAL version 3.1.2.

I setup a stripmapStack run and started the `run_1_reference` script generated by the `stackStripMap.py` command. It seems to run the topo processing to generate all the full-resolution geometry files in `merged/geom_reference`, but then the multilooking step fails. I wonder if this new version of GDAL is not compatible. Folks found an issue in ARIA-tools where versions of GDAL greater than 3.0.4 cause errors (https://github.com/aria-tools/ARIA-tools/issues/232)
```
...
GDAL close: /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/merged/geom_reference/hgt.rdr.vrt
API close:  /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/merged/geom_reference/simamp.rdr
Warning 1: Geotransform matrix has non rotational terms
ERROR 4: /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/geom_reference/hgt.rdr.vrt: No such file or directory
C pointer already created. Finalize and recreate if image dimensions changed.
C pointer already created. Finalize and recreate if image dimensions changed.
--------------------------------------------------
generate multilooked geometry files with alks=16 and rlks=4 using gdal.Translate() ...
multilook /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/merged/geom_reference/hgt.rdr
.vrt
/u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/geom_reference/hgt.rdr
Traceback (most recent call last):
  File "/u/pez0/fielding/tools/ISCE2_test/isce2/contrib/stack/stripmapStack/stripmapWrapper.py", line 155, in <module>
    main(args.start,args.end)
  File "/u/pez0/fielding/tools/ISCE2_test/isce2/contrib/stack/stripmapStack/stripmapWrapper.py", line 146, in main
    cfgParser.runCmd()
  File "/u/pez0/fielding/tools/ISCE2_test/isce2/contrib/stack/stripmapStack/stripmapWrapper.py", line 51, in runCmd
    func_modules.main(self.funcParams[section])
  File "/u/pez0/fielding/tools/ISCE2_test/isce2/contrib/stack/stripmapStack/topo.py", line 525, in main
    runMultilook(in_dir=info.outdir, out_dir=out_dir, alks=inps.alks, rlks=inps.rlks)
  File "/u/pez0/fielding/tools/ISCE2_test/isce2/contrib/stack/stripmapStack/topo.py", line 423, in runMultilook
    gdal2isce_xml(out_file+'.vrt')
  File "/u/pez0/fielding/tools/ISCE2_test/install/isce/applications/gdal2isce_xml.py", line 69, in gdal2isce_xml
    width = ds.RasterXSize
AttributeError: 'NoneType' object has no attribute 'RasterXSize'
```

**Comment by rtburns-jpl** [comment]
Hmm, do you see anything concerning here: https://github.com/OSGeo/gdal/blob/v3.1.0/gdal/MIGRATION_GUIDE.TXT#L1-L68
Maybe you could also try `gdal.UseExceptions()` to see if it gives a more helpful message?

**Comment by EJFielding** [comment]
I added `gdal.UseExceptions()` to the `isce/applications/gdal2isce_xml.py` code and I get a different message now:
```
GDAL open (R): /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/merged/geom_reference/hgt.rdr.vrt
API open (WR): /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/merged/geom_reference/simamp.rdr
GDAL open (R): /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/merged/geom_reference/hgt.rdr.vrt
GDAL close: /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/merged/geom_reference/hgt.rdr.vrt
API close:  /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/merged/geom_reference/simamp.rdr
Warning 1: Geotransform matrix has non rotational terms
C pointer already created. Finalize and recreate if image dimensions changed.
C pointer already created. Finalize and recreate if image dimensions changed.
--------------------------------------------------
generate multilooked geometry files with alks=16 and rlks=4 using gdal.Translate() ...
multilook /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/merged/geom_reference/hgt.rdr
.vrt
/u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/geom_reference/hgt.rdr
Traceback (most recent call last):
  File "/u/pez0/fielding/tools/ISCE2_test/isce2/contrib/stack/stripmapStack/stripmapWrapper.py", line 155, in <module>
    main(args.start,args.end)
  File "/u/pez0/fielding/tools/ISCE2_test/isce2/contrib/stack/stripmapStack/stripmapWrapper.py", line 146, in main
    cfgParser.runCmd()
  File "/u/pez0/fielding/tools/ISCE2_test/isce2/contrib/stack/stripmapStack/stripmapWrapper.py", line 51, in runCmd
    func_modules.main(self.funcParams[section])
  File "/u/pez0/fielding/tools/ISCE2_test/isce2/contrib/stack/stripmapStack/topo.py", line 525, in main
    runMultilook(in_dir=info.outdir, out_dir=out_dir, alks=inps.alks, rlks=inps.rlks)
  File "/u/pez0/fielding/tools/ISCE2_test/isce2/contrib/stack/stripmapStack/topo.py", line 423, in runMultilook
    gdal2isce_xml(out_file+'.vrt')
  File "/u/pez0/fielding/tools/ISCE2_test/install/isce/applications/gdal2isce_xml.py", line 70, in gdal2isce_xml
    ds =  gdal.Open(fname, gdal.GA_ReadOnly)
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/isce2/lib/python3.8/site-packages/osgeo/gdal.py", line 4192, in Open
    return _gdal.Open(*args)
RuntimeError: /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s1/geom_reference/hgt.rdr.vrt: No such file or directory
```
It is creating the `s1/geom_reference/hgt.rdr` file along with `s1/geom_reference/hgt.hdr` and `s1/geom_reference/hgt.rdr.aux.xml` files, but it is not creating the `s1/geom_reference/hgt.rdr.vrt` file for some reason.

**Comment by yunjunz** [comment]
It seems like the *.vrt file is not created by the `gdal.Translate()` call in [topo.py#L418](https://github.com/isce-framework/isce2/blob/main/contrib/stack/stripmapStack/topo.py#L418), adding the following two lines below L418 should fix it. Could you confirm @EJFielding?

```
ds = gdal.Open(out_file, gdal.GA_ReadOnly)
gdal.Translate(out_file+'.vrt', ds, options=gdal.TranslateOptions(format='VRT'))
```

**Comment by EJFielding** [comment]
Thanks @yunjunz. I tried adding that and it did fix the issue for me. I sent a PR.

**Comment by EJFielding** [comment]
The PR #196 change worked and the `geom_reference` output files were created, including the watermask download and reprojection. I was able to load the resulting UAVSAR stack into MintPy. Here is the view of the geometry data:
![geometryRadar](https://user-images.githubusercontent.com/7253576/97051997-0d912c80-1535-11eb-9d22-dbdb895274af.png)
It looks like there is another much smaller problem with the incidenceAngle and azimuthAngle files that might not have the right data type set.
