### ISSUE TITLE
run_3_geo2rdr_coarseResamp error (stackStripMap.py) 

### ISSUE THREAD

**Issue by stoormgeo** [isce-framework/isce2#201]
Hi,
Does anyone know any solution for this issue?
Slc data is present as 20170630.slc  20170630.slc.vrt 20170630.slc.xml  data.db in each directory.
But after starting the 3rd stage i have only data.db file in the /data/insar/Proc/YLPG/proc/coregSLC/Coarse/20170630/referenceShelve and secondaryShelve folders.
I checked the permissions and it is ok.

**Running: resampleSlc**
['--reference', '/data/insar/Proc/YL/SLC/20170629', '--secondary', '/data/insar/Proc/YL/SLC/20170630', '--coreg', '/data/insar/Proc/YL/proc/coregSLC/Coarse/20170630', '--offsets', '/data/insar/Proc/YL/proc/offsets/20170630']
cp /data/insar/Proc/YL/SLC/20170630/data* /data/insar/Proc/YL/proc/coregSLC/Coarse/20170630/secondaryShelve
Traceback (most recent call last):
  File "/opt/isce2/isce/contrib/stack/stripmapStack/stripmapWrapper.py", line 155, in <module>
    main(args.start,args.end)
  File "/opt/isce2/isce/contrib/stack/stripmapStack/stripmapWrapper.py", line 146, in main
    cfgParser.runCmd()
  File "/opt/isce2/isce/contrib/stack/stripmapStack/stripmapWrapper.py", line 51, in runCmd
    func_modules.main(self.funcParams[section])
  File "/opt/isce2/isce/contrib/stack/stripmapStack/resampleSlc.py", line 219, in main
    reference = reference)
  File "/opt/isce2/isce/components/isceobj/Util/decorators.py", line 290, in use_api_decorator
    ret = func(*args,**kwargs)
  File "/opt/isce2/isce/contrib/stack/stripmapStack/resampleSlc.py", line 106, in resampSecondary
    inimg.load(burst.getImage().filename + '.xml')
  File "/opt/isce2/isce/components/iscesys/Component/Configurable.py", line 1407, in load
    tmpProp, tmpFact, tmpMisc = FP.parse(filename)
  File "/opt/isce2/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse
    root = ET.parse(filename)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
**FileNotFoundError: [Errno 2] No such file or directory: './20170630/20170630.slc.xml'**

**Comment by xialuwen** [comment]
我遇到了一样的问题，请问你解决了吗
