### ISSUE TITLE
Error: from stripmapApp import Insar   ImportError: /home/rsgis/miniconda3/envs/isce/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-x86_64-linux-gnu.so: undefined symbol: VSIGetFileSystemOptions

### ISSUE THREAD

**Issue by neverstoplearn** [isce-framework/isce2#210]
I successfully installed ISCE, when I  use command import isce I Got the right result.But when I  use from stripmapApp import Insar I got error
![10](https://user-images.githubusercontent.com/44988584/101791167-2f269180-3b3e-11eb-8dc2-a1f946f81da9.png)
How can I fix it? thanks.

**Comment by neverstoplearn** [comment]
`(isce) rsgis@rsgis10:/mnt/isce2$ python3
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import isce
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
>>> from stripmapApp import Insar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/isce2/install/isce/applications/stripmapApp.py", line 47, in <module>
    import isceobj.StripmapProc as StripmapProc
  File "/mnt/isce2/install/isce/components/isceobj/StripmapProc/__init__.py", line 34, in <module>
    from .Factories import *
  File "/mnt/isce2/install/isce/components/isceobj/StripmapProc/Factories.py", line 106, in <module>
    createCrop = _factory("runCrop")
  File "/mnt/isce2/install/isce/components/isceobj/StripmapProc/Factories.py", line 22, in _factory
    _PATH+name, fromlist=[""]
  File "/mnt/isce2/install/isce/components/isceobj/StripmapProc/runCrop.py", line 9, in <module>
    from imageMath import IML
  File "/mnt/isce2/install/isce/applications/imageMath.py", line 42, in <module>
    from isceobj.Util.ImageUtil import ImageLib as IML
  File "/mnt/isce2/install/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 344, in <module>
    class memmapGDAL(object):
  File "/mnt/isce2/install/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 349, in memmapGDAL
    from osgeo import gdal
  File "/home/rsgis/miniconda3/envs/isce/lib/python3.6/site-packages/osgeo/__init__.py", line 26, in <module>
    _gdal = swig_import_helper()
  File "/home/rsgis/miniconda3/envs/isce/lib/python3.6/site-packages/osgeo/__init__.py", line 22, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/rsgis/miniconda3/envs/isce/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/rsgis/miniconda3/envs/isce/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/rsgis/miniconda3/envs/isce/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-x86_64-linux-gnu.so: undefined symbol: VSIGetFileSystemOptions
`

**Comment by neverstoplearn** [comment]
And when I try topsApp.py --steps --help
I got this error:
`(isce) rsgis@rsgis10:/mnt/isce2$ topsApp.py --steps --help
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Traceback (most recent call last):
  File "/mnt/isce2/install/isce/applications/topsApp.py", line 1039, in <module>
    insar = TopsInSAR(name="topsApp")
  File "/mnt/isce2/install/isce/applications/topsApp.py", line 684, in __init__
    cmdline=cmdline)
  File "/mnt/isce2/install/isce/components/iscesys/Component/Application.py", line 432, in __init__
    super(Application, self).__init__(family=family, name=name)
  File "/mnt/isce2/install/isce/components/iscesys/Component/Component.py", line 166, in __init__
    super(Component, self).__init__(family, name)
  File "/mnt/isce2/install/isce/components/iscesys/Component/Configurable.py", line 1650, in __init__
    help = Helper()
  File "/mnt/isce2/install/isce/applications/iscehelp.py", line 552, in __init__
    self._registered = self.getRegistered()
  File "/mnt/isce2/install/isce/applications/iscehelp.py", line 35, in getRegistered
    helplist = os.listdir(self._helpDir)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/isce2/install/isce/helper'
(isce) rsgis@rsgis10:/mnt/isce2$ 
`
`

**Comment by neverstoplearn** [comment]
I   reinstall the gdal 3.2.0, and reinstall isce, I can run `import isce` successfully,but when I run `from stripmapApp import Insar `  I meet another error,`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/isce2/install/isce/applications/stripmapApp.py", line 47, in <module>
    import isceobj.StripmapProc as StripmapProc
  File "/mnt/isce2/install/isce/components/isceobj/StripmapProc/__init__.py", line 33, in <module>
    from .StripmapProc import *
  File "/mnt/isce2/install/isce/components/isceobj/StripmapProc/StripmapProc.py", line 14, in <module>
    from isceobj.Scene.Frame import FrameMixin
  File "/mnt/isce2/install/isce/components/isceobj/Scene/Frame.py", line 34, in <module>
    from isceobj.Image.Image import Image
  File "/mnt/isce2/install/isce/components/isceobj/Image/Image.py", line 38, in <module>
    from iscesys.ImageApi.DataAccessorPy import DataAccessor
  File "/mnt/isce2/install/isce/components/iscesys/ImageApi/DataAccessorPy.py", line 31, in <module>
    from iscesys.ImageApi import DataAccessor as DA
ImportError: libgdal.so.28: cannot open shared object file: No such file or directory
`
can anyone help me? thanks.

**Comment by aivazis** [comment]
It appears that the dynamic linker cannot find the `gdal` libraries. Have you tries adding the location of the `gdal` libraries to your `LD_LIBRARY_PATH`?

**Comment by neverstoplearn** [comment]
I notices that the error is can not find the libgdal.so.28, I use `whereis libgdal`,I find `/usr/lib` have  'libgdal.a libgdal.so libgdal.so.20 libgdal.so.20.3.2' but I can not find libgdal.so.28. then I add `LD_LIBRARY_PATH = /usr/lib:$LD_LIBRARY_PATH`, but I meet the same error, am I install the gdal wrong.
