### ISSUE TITLE
stackSentinel.py couldn't recognize the orbit EOF file and download it

### ISSUE THREAD

**Issue by mohseniaref-InSAR** [isce-framework/isce2#249]
Dear all,

It seems stackSentinel.py can not recognize downloaded EOF in folder and try to download file . I really appreciate if you can help me in order to solve this issue
```
stackSentinel.py  -s /raid/maref/InSAR/S1/desc_tr10_f -o /raid-manaslu/maref/InSAR/ORBIT/aux_poeorb/  -a /raid/maref/InSAR/ORBIT/aux_ins/ -d demLat_S28_S22_Lon_W070_W062.dem.wgs84 -m 20150814  -c all -W slc  -b '-25.3 -24.0 -66.2 -65.2' 2>&1 | tee stackSentinel.log
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Number of SAFE files found: 280
2021-03-05 23:33:35,219 - shapely.geos - DEBUG - Found GEOS DLL: <CDLL '/raid-manaslu/maref/Software/anaconda3/envs/myisceenv/lib/python3.8/site-packages/shapely/.libs/libgeos_c-a68605fd.so.1.13.1', handle 55cc50d93ba0 at 0x7f67ec742cd0>, using it.
2021-03-05 23:33:35,235 - shapely.geos - DEBUG - Trying `CDLL(libc.so.6)`
2021-03-05 23:33:35,236 - shapely.geos - DEBUG - Library path: 'libc.so.6'
2021-03-05 23:33:35,236 - shapely.geos - DEBUG - DLL: <CDLL 'libc.so.6', handle 7f6909e879d0 at 0x7f67ec753640>
Reference time:  2019-01-31 09:44:50
Satellite name:  S1B
https://qc.sentinel1.eo.esa.int/aux_poeorb/?validity_start=2019-01-29..2019-02-02&sentinel1__mission=S1B
Querying for precise orbits
Exception - something went wrong with the web scraper:
Exception: HTTPSConnectionPool(host='qc.sentinel1.eo.esa.int', port=443): Max retries exceeded with url: /aux_poeorb/?validity_start=2019-01-29..2019-02-02&sentinel1__mission=S1B (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f52a2137a30>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Continuing process
Failed to find precise orbits for Time 2019-01-31 09:44:50
https://qc.sentinel1.eo.esa.int/aux_resorb/?validity_start=2019-01-30..2019-02-01&sentinel1__mission=S1B
Querying for restituted orbits
Exception - something went wrong with the web scraper:
Exception: HTTPSConnectionPool(host='qc.sentinel1.eo.esa.int', port=443): Max retries exceeded with url: /aux_resorb/?validity_start=2019-01-30..2019-02-01&sentinel1__mission=S1B (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f52a2126b80>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Continuing process
Failed to find restituted orbits for Time 2019-01-31 09:44:50
*****************************************
20190131
orbit was not found in the /raid-manaslu/maref/InSAR/ORBIT/aux_poeorb
downloading precise or restituted orbits ...
fetchOrbit.py -i /raid/maref/InSAR/S1/desc_tr10_f/S1B_IW_SLC__1SDV_20190131T094423_20190131T094450_014736_01B7A3_97A4.zip -o /raid/maref/InSAR/S1/desc_tr10_f/orbits/20190131
Traceback (most recent call last):
  File "/raid-manaslu/maref/Software/isce251/contrib/stack/topsStack/stackSentinel.py", line 772, in <module>
    main(sys.argv[1:])
  File "/raid-manaslu/maref/Software/isce251/contrib/stack/topsStack/stackSentinel.py", line 735, in main
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict, updateStack = checkCurrentStatus(inps)
  File "/raid-manaslu/maref/Software/isce251/contrib/stack/topsStack/stackSentinel.py", line 611, in checkCurrentStatus
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict = get_dates(inps)
  File "/raid-manaslu/maref/Software/isce251/contrib/stack/topsStack/stackSentinel.py", line 275, in get_dates
    safeObj.get_orbit(inps.orbit_dirname, inps.work_dir)
  File "/raid/maref/Software/isce251/contrib/stack/topsStack/Stack.py", line 1048, in get_orbit
    self.orbit =  orbitFile[0]
IndexError: list index out of range
``

**Comment by piyushrpt** [comment]
The S1 orbits site is no longer active. The script for automated downloads needs to be updated to use `aux.sentinel1.eo.esa.int` instead. If you have a local copy of the orbits in a folder, it should work.

**Comment by mohseniaref-InSAR** [comment]
@piyushrpt  Thanks for your response! The orbits are located in the folder as you see. I am surprised because of that.It doesn't work and I don't get why . Would you please guide me to solve this issue?
```
 ls /raid-manaslu/maref/InSAR/ORBIT/aux_poeorb/*20190131*
/raid-manaslu/maref/InSAR/ORBIT/aux_poeorb/S1A_OPER_AUX_POEORB_OPOD_20190131T120833_V20190110T225942_20190112T005942.EOF
/raid-manaslu/maref/InSAR/ORBIT/aux_poeorb/S1A_OPER_AUX_POEORB_OPOD_20190219T120745_V20190129T225942_20190131T005942.EOF
/raid-manaslu/maref/InSAR/ORBIT/aux_poeorb/S1A_OPER_AUX_POEORB_OPOD_20190221T120828_V20190131T225942_20190202T005942.EOF
/raid-manaslu/maref/InSAR/ORBIT/aux_poeorb/S1B_OPER_AUX_POEORB_OPOD_20190131T110643_V20190110T225942_20190112T005942.EOF
/raid-manaslu/maref/InSAR/ORBIT/aux_poeorb/S1B_OPER_AUX_POEORB_OPOD_20190219T110622_V20190129T225942_20190131T005942.EOF
/raid-manaslu/maref/InSAR/ORBIT/aux_poeorb/S1B_OPER_AUX_POEORB_OPOD_20190221T110733_V20190131T225942_20190202T005942.EOF

/raid-manaslu/maref/InSAR/ORBIT/aux_poeorb/20190131:
S1A_OPER_AUX_POEORB_OPOD_20190131T120833_V20190110T225942_20190112T005942.EOF  S1B_OPER_AUX_POEORB_OPOD_20190131T110643_V20190110T225942_20190112T005942.EOF
S1A_OPER_AUX_POEORB_OPOD_20190219T120745_V20190129T225942_20190131T005942.EOF  S1B_OPER_AUX_POEORB_OPOD_20190219T110622_V20190129T225942_20190131T005942.EOF
S1A_OPER_AUX_POEORB_OPOD_20190221T120828_V20190131T225942_20190202T005942.EOF  S1B_OPER_AUX_POEORB_OPOD_20190221T110733_V20190131T225942_20190202T005942.EOF

```

**Comment by piyushrpt** [comment]
I dont actually see a usable orbit file for `20190131` in that folder. Look at the last 2 time tags carefully, none of the files cover that date except the first and last hours.

**Comment by mohseniaref-InSAR** [comment]
@piyushrpt  Thank you!
