### ISSUE TITLE
conda-forge dependencies

### ISSUE THREAD

**Issue by RussellGrew** [isce-framework/isce2#275]
I just installed ISCE2 on a fresh Ubuntu server from conda forge, technically with mamba as I have found it faster than conda for working out dependencies. 

https://anaconda.org/conda-forge/isce2/

```
conda install mamba -c conda-forge
mamba install isce2 -c conda-forge
```

For reference there were two issues which I tried running `stackSentinel.py`

```
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

solved by `sudo apt install libgl1-mesa-glx`

And `ModuleNotFoundError: No module named 'shapely'` which needed a simple `pip install shapely`

Thanks for maintaining the conda-forge package. I have never tried building with SCons but this seems very convenient.

**Comment by danschef** [comment]
I just ran into this (quite old) issue. Here is more detailed traceback about the failed shapely import (triggered by some code frour side):

```python
Traceback (most recent call last):
  File "/builds/ipi-sar4infra/preprocessing/preprocessing/preprocessing_cli.py", line 107, in runPreprocessing
    stackSentinel.main(iargs=cmd)
  File "/opt/conda/envs/ci_env/share/isce2/topsStack/stackSentinel.py", line 985, in main
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict, updateStack = checkCurrentStatus(inps)
                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ci_env/share/isce2/topsStack/stackSentinel.py", line 878, in checkCurrentStatus
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict = get_dates(inps)
                                                                      ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ci_env/share/isce2/topsStack/stackSentinel.py", line 321, in get_dates
    pnts_polygon = generate_geopolygon(pnts_bbox)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ci_env/share/isce2/topsStack/stackSentinel.py", line 229, in generate_geopolygon
    from shapely.geometry import Point, Polygon
ModuleNotFoundError: No module named 'shapely'
```

Adding shapely to the run-requirements [here](https://github.com/conda-forge/isce2-feedstock/blob/a8d1398b9b6731b6c3090daf2ad5d7150e6a8801/recipe/meta.yaml#L39) (and probably also opencv) should fix it, at least for the conda-forge builds.
