### ISSUE TITLE
How to change the snaphu to version 2.0

### ISSUE THREAD

**Issue by SiriusXCH0103** [isce-framework/isce2#298]
The version of Snaphu module integrated in ISCE is v1.4.2. 
I downloaded the source code of Snaphu 2.0.4 and replaced the *.h and *.c files in ISCE package: isce2/contrib/Snaphu/include and isce2/contrib/Snaphu/src, then recompiled. 
However, it reported an error when processing. It cannot import Snaphu module.
How to change the snaphu version?  Can it only use version 1.4?

`ISCE VERSION = 2.5.2, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20210528, CURRENT_SVN_REVISION = 
Traceback (most recent call last):
  File "/home/xch/isce2/install/isce/applications/topsApp.py", line 1059, in <module>
    insar.configure()
  File "/home/xch/isce2/install/isce/components/iscesys/Component/Configurable.py", line 1461, in configure
    self._configureThis()
  File "/home/xch/isce2/install/isce/components/iscesys/Component/Configurable.py", line 1564, in _configureThis
    self.init(self.catalog,self._dictionaryOfFacilities,unitsDict,docDict)
  File "/home/xch/isce2/install/isce/components/iscesys/Component/Configurable.py", line 704, in init
    self.initRecursive(self.catalog,self._dictionaryOfFacilities)
  File "/home/xch/isce2/install/isce/components/iscesys/Component/Configurable.py", line 826, in initRecursive
    comp = factoryobject(*args, **kwargs)
  File "/home/xch/isce2/install/isce/components/isceobj/TopsProc/Factories.py", line 53, in createUnwrapper
    from .runUnwrapSnaphu import runUnwrapMcf as runUnwrap
  File "/home/xch/isce2/install/isce/components/isceobj/TopsProc/runUnwrapSnaphu.py", line 8, in <module>
    from contrib.Snaphu.Snaphu import Snaphu
  File "/home/xch/isce2/install/isce/components/contrib/Snaphu/Snaphu.py", line 34, in <module>
    from . import snaphu
ImportError: /home/xch/isce2/install/isce/components/contrib/Snaphu/snaphu.abi3.so: undefined symbol: snaphu
`

**Comment by EJFielding** [comment]
The ISCE2 modules use special libraries to read and write images. You can't take the regular source code for Snaphu 2.x and substitute it into ISCE without changing the parts of the code that do the image reading and writing.
