### ISSUE TITLE
Exception: No SAFE file found

### ISSUE THREAD

**Issue by PeymanPython** [isce-framework/isce2#330]
Hello guys, 
Could anyone tell me what's the matter? I am running the following code to get configs/run_files and orbits ... but it doesn't work. 
Of course, I've searched several times in submitted issues but nothing's been found in such theme (I believe that the ex-version of ISCE Forum was more user-friendly than this).
Thanks in advance..

stackSentinel.py -s home/user/tools/MirAhmad/SLC/ -d home/user/tools/MirAhmad/DEM/demLat_N31_N32_Lon_E049_E051.dem.wgs84 -a home/user/tools/MirAhmad/AuxFile/ -o home/user/tools/MirAhmad/OrbitFile/ -b '31 32 49 51' -c all -W slc
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Traceback (most recent call last):
  File "/home/user/tools/isce2-main/contrib/stack/topsStack/stackSentinel.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/user/tools/isce2-main/contrib/stack/topsStack/stackSentinel.py", line 735, in main
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict, updateStack = checkCurrentStatus(inps)
  File "/home/user/tools/isce2-main/contrib/stack/topsStack/stackSentinel.py", line 611, in checkCurrentStatus
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict = get_dates(inps)
  File "/home/user/tools/isce2-main/contrib/stack/topsStack/stackSentinel.py", line 241, in get_dates
    raise Exception('No SAFE file found')
Exception: No SAFE file found

May you want to see the SLC folder contents... or its address
![Screenshot from 2021-08-26 16-40-52](https://user-images.githubusercontent.com/55481769/130960801-194dd5a3-a85c-4f16-a521-4beefed5d127.png)

**Comment by PeymanPython** [comment]
Dear Piyush,
Many thanks for your prompt reply...
