### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by PeymanPython** [isce-framework/isce2#338]
Hello Everyone,
After running the code I came across the following error. 

(insar) user@user-B250-HD3:~/tools/MirAhmad$ stackSentinel.py -s /home/user/tools/MirAhmad/SLC/ -d /home/user/tools/MirAhmad/DEM/demLat_N30_N33_Lon_E049_E052.dem.wgs84 -a /home/user/tools/MirAhmad/AuxFile/ -o /home/user/tools/MirAhmad/orbits/ -b '30 33 49 52' -m 20200626 -n '2' -z 2 -r 8 -c 4 -u snaphu

All SLCs will be coregistered to : 20200626
Traceback (most recent call last):
  File "/home/user/tools/isce2-main/contrib/stack/topsStack/stackSentinel.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/user/tools/isce2-main/contrib/stack/topsStack/stackSentinel.py", line 735, in main
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict, updateStack = checkCurrentStatus(inps)
  File "/home/user/tools/isce2-main/contrib/stack/topsStack/stackSentinel.py", line 611, in checkCurrentStatus
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict = get_dates(inps)
  File "/home/user/tools/isce2-main/contrib/stack/topsStack/stackSentinel.py", line 410, in get_dates
    secondaryList.remove(inps.reference_date)
ValueError: list.remove(x): x not in list
(insar) user@user-B250-HD3:~/tools/MirAhmad$ 

Could anyone please explain the meaning of? Many thanks..

**Comment by PickleRickrx** [comment]
hello,i have the same error,would you please tell me how to fix it?
