### ISSUE TITLE
How to run ALOS2 SLC stacking

### ISSUE THREAD

**Issue by S-Nari** [isce-framework/isce2#344]
Hello.

I'm preparing stacking of ALOS2 stripmap (SM1 mode) for StaMPS PS-InSAR.
I use scripts under /contrib/stack/stripmapStack.

I followed the instructions in 'README.md' & in Yunjun's PR article about prepSlcALOS2.py.

My workflow is as follows.

At the 5th step (run_01_crop), 
I got an error message that there is no estimated doppler valued in the array 'coeff'.

How can I correctly handle the scrips of ALOS2 SLC stacking ?
I will appreciate if you tell me how to use.

S. Narita

---------------------------------------------------------------
Workflow:

1, prepSlcALOS2.py
   $ prepSlcALOS2.py -i download/  -o SLC

2, prepRawSensor.py
   $ prepRawSensor.py -i download/ -o SLC

3, unpackFrame_ALOS2.py

   $source ~/.bash_profile;unpackFrame_ALOS2.py -i /media/narita-t140/Elements1/ISCE2_proc/kuju_130A_proc/stacking/download/20140828 -o /media/narita-t140/Elements1/ISCE2_proc/kuju_130A_proc/stacking/SLC/20140828
   (in the script 'run_unPackALOS2')
    
    (Q. Deskew option '-d' is necessary ??)

4, stackStripMap.py
 
  $ stackStripMap.py -s SLC/ -d DEM/demLat_N32_N34_Lon_E130_E132.dem.wgs84 -t 3650 -b 4000 -a 1 -r 1 -u snaphu -f 0 -W slc  -x '33.0590 33.1500 131.1280 131.2960'  -S alos2  -m 20170601 --nofocus -z

5,  run_01_crop
    $ stripmapWrapper.py -c /media/narita-t140/Elements1/ISCE2_proc/kuju_130A_proc/stacking/configs/config_crop_20140828

Completed Parsing the Configuration file
Running: cropFrame
['--input', '/media/narita-t140/Elements1/ISCE2_proc/kuju_130A_proc/stacking/SLC/20140828', '--box_str', '33.0590 33.1500 131.1280 131.2960', '--output', '/media/narita-t140/Elements1/ISCE2_proc/kuju_130A_proc/stacking/SLC_crop/20140828']

(print frame)
Sensing Start Time: (2014-08-28 15:11:49.887401)
Sensing Mid Time: (2014-08-28 15:11:54.887441)
Sensing Stop Time: (2014-08-28 15:11:59.887482)
Orbit Number: (1427)
Frame Number: (40828)
Track Number: (None)
Number of Lines: (32521)
Number of Samples: (23344)
Starting Range: (751562)
Polarization: (HH)
Processing Facility: (EICS)
Processing Software: (EICS)
Processing Software Version: (002.012)

Polynomial Order: 0 - by - 0 
0	
Line start:  15119.0
Line stop:  23193.0
Line limits:  15119 23193
Original Line Limits:  0 32521
Pixel start:  1297.0
Pixel stop:  14546.0
Pixel limits:  1297 14546
Original Pixel Limits:  0 23344
Traceback (most recent call last):
  File "/home/narita-t140/isce_tools/isce2-main/contrib/stack/stripmapStack/stripmapWrapper.py", line 155, in <module>
    main(args.start,args.end)
  File "/home/narita-t140/isce_tools/isce2-main/contrib/stack/stripmapStack/stripmapWrapper.py", line 146, in main
    cfgParser.runCmd()
  File "/home/narita-t140/isce_tools/isce2-main/contrib/stack/stripmapStack/stripmapWrapper.py", line 51, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/narita-t140/isce_tools/isce2-main/contrib/stack/stripmapStack/cropFrame.py", line 299, in main
    outFrame = cropFrame(frame, limits, inps.outdir, israw=inps.israw)
  File "/home/narita-t140/isce_tools/isce2-main/contrib/stack/stripmapStack/cropFrame.py", line 209, in cropFrame
    rng = np.linspace(xmin, xmax, len(coeff) + 1)
TypeError: object of type 'NoneType' has no len()

**Comment by yunjunz** [comment]
You should run `prepSlcALOS2.py`, and do not run `prepRawSensor.py`, if I understand your workflow correctly.

**Comment by S-Nari** [comment]
Thank you for your reply.

I used `prepSlcALOS2.py`.

Now, I've just retried the workflow without `prepRawSensor.py`, and manually unpack using `unpackFrame_ALOS2.py`, as you pointed out.
But I've got the same error about no doppler value in the 'coeff' in `cropFrame.py.`

In `cropFrame.py`,
```
    ####Adjust Doppler centroid coefficients
    coeff = frame._dopplerVsPixel
    rng = np.linspace(xmin, xmax, len(coeff) + 1) 
```
'coeff' is assigned from 'frame._dopplerVsPixel', 
but in `unpackFrame_ALOS2.py`,
it seems that 'obj.frame._dopplerVsPixel' is not defined.

Alterenatively, in `unpackFrame_ALOS2.py`,
` coeffs = obj.doppler_coeff`
'coeffs' is assigned from 'obj.doppler_coeff' (altough I dont know if 'coeff' and 'coeffs' are same or not...).

(in contrast, `unpackFrame_ALOS_raw.py` explicitly defines 'frame._dopplerVsPixel' )

I add the following line into `unpackFrame_ALOS2.py`,  
and run_01_crop (cropFrame.py) has worked well.

`obj.frame._dopplerVsPixel = obj.doppler_coeff`

However, I don't know if this modification is really correct or not...
