### ISSUE TITLE
Error running "run_04_refineSecondaryTiming" for ALOS1 stack.

### ISSUE THREAD

**Issue by Dani-Lindsay** [isce-framework/isce2#381]
### Discussed in https://github.com/isce-framework/isce2/discussions/380

<div type='discussions-op-text'>

<sup>Originally posted by **Dani-Lindsay** November  5, 2021</sup>
Hi there, 

I am using stackStripMap.py to generate a ALOS-1 stack and am having trouble running "run_04_refineSecondaryTiming" with stripmapWrapper.py -c /global/scratch/users/daniellelindsay/CC_ALOS1/proc/201A/configs/config_refineSecondaryTiming_20060905_20061206. 

I keep getting the error below...  

```
2021-11-05 14:02:34,297 - isceobj.Location.OffsetField - INFO - 0 offsets culled
Error. Trying to allocate zero size array
Traceback (most recent call last):
  File "/global/home/users/daniellelindsay/.conda/envs/isce2_3.8/share/isce2/stripmapStack/stripmapWrapper.py", line 155, in <module>
    main(args.start,args.end)
  File "/global/home/users/daniellelindsay/.conda/envs/isce2_3.8/share/isce2/stripmapStack/stripmapWrapper.py", line 146, in main
    cfgParser.runCmd()
  File "/global/home/users/daniellelindsay/.conda/envs/isce2_3.8/share/isce2/stripmapStack/stripmapWrapper.py", line 51, in runCmd
    func_modules.main(self.funcParams[section])
  File "/global/home/users/daniellelindsay/.conda/envs/isce2_3.8/share/isce2/stripmapStack/refineSecondaryTiming.py", line 221, in main
    shifts, cull = fitOffsets(field,azazOrder=inps.azazorder,
  File "/global/home/users/daniellelindsay/.conda/envs/isce2_3.8/share/isce2/stripmapStack/refineSecondaryTiming.py", line 149, in fitOffsets
    objOff.offoutliers()
  File "/global/home/users/daniellelindsay/.conda/envs/isce2_3.8/lib/python3.8/site-packages/isce/components/isceobj/Util/Offoutliers.py", line 87, in offoutliers
    self.allocateArrays()
  File
"/global/home/users/daniellelindsay/.conda/envs/isce2_3.8/lib/python3.8/site-packages/isce/components/isceobj/Util/Offoutliers.py", line 191, in allocateArrays
    raise Exception
Exception
```
I am running the jobs using GNU parallel on an hpc system, however if I also just try running each line individually (adding #!/bin/bash at the top of the cmd file and make executable) I get the same error.

```
parallel < run_files/run_04_refineSecondaryTiming &> logs/run_04.log
```

If anyone has suggestions for input parameters or something I could try to fix this I would be very appreciative. 

Attached are my log files. 
[run_01.log](https://github.com/isce-framework/isce2/files/7488996/run_01.log)
[run_02.log](https://github.com/isce-framework/isce2/files/7488997/run_02.log)
[run_03.log](https://github.com/isce-framework/isce2/files/7488998/run_03.log)
[run_04.log](https://github.com/isce-framework/isce2/files/7488999/run_04.log)
[run_05.log](https://github.com/isce-framework/isce2/files/7489000/run_05.log)
[run_06.log](https://github.com/isce-framework/isce2/files/7489001/run_06.log)
[run_07.log](https://github.com/isce-framework/isce2/files/7489002/run_07.log)
[run_08.log](https://github.com/isce-framework/isce2/files/7489003/run_08.log)
 

 </div>

**Comment by piyushrpt** [comment]
Make sure that the images you are trying to create a stack that covers your AOI are from the same track. This error essentially means it found zero matches to tie the images. Either the scene being used is not from the same track or frame. Use mdx.py to look at the SLCs for those dates to make sure they look correct.

**Comment by Dani-Lindsay** [comment]
This was exactly the problem, thank you! I downloaded the data with ssara and forgot to visually inspect. Even though they have the same track and frame numbers there is one date which doesn't overlap with the others. 

![Screen Shot 2021-11-08 at 4 10 07 PM](https://user-images.githubusercontent.com/71908495/140838034-09698e9d-f437-450e-953a-471b85b3db7f.png)

**Comment by zhuhaxixiong** [comment]
I also get the error when do run_04_refineSecondaryTiming of ALOS1 stack ,but my data wa cover the same region
