### ISSUE TITLE
orbit file not getting downloaded using stackStentinel.py

### ISSUE THREAD

**Issue by pritha19** [isce-framework/isce2#421]
Hi,
I am new to the isce2 software and linux.
Everytime am trying to processes the data using stackSentinel.py I am getting the same Index error : list index out of range
####
20190413
orbit was not found in the /home/iirs/pritha/project/orbits
downloading precise or restituted orbits ...
fetchOrbit.py -i /home/iirs/pritha/project/data/slc/S1A_IW_SLC__1SDV_20190413T002849_20190413T002917_026764_0301A2_2FA8.zip -o /home/iirs/pritha/project/orbits/20190413
sh: 1: fetchOrbit.py: not found
Traceback (most recent call last):
  File "/home/iirs/anaconda3/envs/new_env/share/isce2/topsStack/stackSentinel.py", line 787, in <module>
    main(sys.argv[1:])
  File "/home/iirs/anaconda3/envs/new_env/share/isce2/topsStack/stackSentinel.py", line 750, in main
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict, updateStack = checkCurrentStatus(inps)
  File "/home/iirs/anaconda3/envs/new_env/share/isce2/topsStack/stackSentinel.py", line 626, in checkCurrentStatus
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict = get_dates(inps)
  File "/home/iirs/anaconda3/envs/new_env/share/isce2/topsStack/stackSentinel.py", line 283, in get_dates
    safeObj.get_orbit(inps.orbit_dirname, inps.work_dir)
  File "/home/iirs/anaconda3/envs/new_env/share/isce2/topsStack/Stack.py", line 1048, in get_orbit
    self.orbit =  orbitFile[0]
IndexError: list index out of range

###
can you please tell how to resolve this.

**Comment by RussellGrew** [comment]
It looks like it cannot find fetchOrbit.py and you probably need to add the topStack tools to your path like
```
export PATH=/home/iirs/anaconda3/envs/new_env/share/isce2/contrib/stack/topsStack:$PATH;
```
following advice at https://github.com/isce-framework/isce2/tree/main/contrib/stack

You could add that command to your `~/.bashrc` file so it is remembered.

Good luck!

**Comment by pritha19** [comment]
Thank you, I followed the steps as you suggested. It downloaded 5 files, but again the same error is showing.

20210108
orbit was not found in the /home/iirs/pritha/project/orbits
downloading precise or restituted orbits ...
fetchOrbit.py -i /home/iirs/pritha/project/data/slc/S1A_IW_SLC__1SDV_20210108T002908_20210108T002936_036039_043921_5541(1).zip -o /home/iirs/pritha/project/orbits/20210108
sh: 1: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "/home/iirs/anaconda3/envs/new_env/share/isce2/topsStack/stackSentinel.py", line 787, in <module>
    main(sys.argv[1:])
  File "/home/iirs/anaconda3/envs/new_env/share/isce2/topsStack/stackSentinel.py", line 750, in main
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict, updateStack = checkCurrentStatus(inps)
  File "/home/iirs/anaconda3/envs/new_env/share/isce2/topsStack/stackSentinel.py", line 626, in checkCurrentStatus
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict = get_dates(inps)
  File "/home/iirs/anaconda3/envs/new_env/share/isce2/topsStack/stackSentinel.py", line 283, in get_dates
    safeObj.get_orbit(inps.orbit_dirname, inps.work_dir)
  File "/home/iirs/anaconda3/envs/new_env/share/isce2/topsStack/Stack.py", line 1048, in get_orbit
    self.orbit =  orbitFile[0]
IndexError: list index out of range

**Comment by bjmarfito** [comment]
@pritha19, I noticed on the error message that the ""(" unexpected". I think the filename is the one causing the error because it was named as S1A_IW_SLC__1SDV_20210108T002908_20210108T002936_036039_043921_5541(1).zip. Kindly remove the (1) on the filename and try processing it again.

**Comment by BianSun** [comment]
I also met the problem😭May I ask if you have finally resolved it？And How did you specifically solve it?
