### ISSUE TITLE
Offset estimation Failed

### ISSUE THREAD

**Issue by durerimon** [isce-framework/isce2#430]
Hi, 
I am relatively new to ISCE. I was running the following code I get an error. My questions are what is causing the issue and how can I solve it? Working on ALOS Palser Images. Any help is appriciated!

``
isce@ISCE:~/Assign2$ insarApp.py --start=rgoffset --end=correct
2022-01-14 22:41:20,171 - isce.insar - INFO - ISCE VERSION = 2.2.0, RELEASE_SVN_REVISION = 2497,RELEASE_DATE = 20180714, CURRENT_SVN_REVISION = Unknown
ISCE VERSION = 2.2.0, RELEASE_SVN_REVISION = 2497,RELEASE_DATE = 20180714, CURRENT_SVN_REVISION = Unknown
Step processing
Loaded the application's pickle object, _insar from file PICKLE/shadecpx2rg
Running step rgoffset
GDAL open (R): resampImage.amp.vrt
GDAL open (R): simamp.rdr.vrt
Bands: 0 0
 Setting first image to real           1
 Setting second image to real           1
 wisdomFile, length =            0
 across step size:    61.6455688    
 down step size:    76.6962051    
 Input lines:        6383        7372
 Input bands:           1           1
 Input widths:        5194        5194
 On line, location            0         187
 On line, location           10         953
 On line, location           20        1720
 On line, location           30        2487
 On line, location           40        3254
 On line, location           50        4021
 On line, location           60        4788
 On line, location           70        5555
2022-01-14 22:41:39,586 - isce.insar.runRgoffset - INFO - 
####################################################################################################
    runRgoffset - Inputs
----------------------------------------------------------------------------------------------------
runRgoffset.inputs.across_gross_offset = 0
runRgoffset.inputs.band1 = 0
runRgoffset.inputs.band2 = 0
runRgoffset.inputs.debug_flag = n
runRgoffset.inputs.down_gross_offset = 0
runRgoffset.inputs.down_spacing_prf1 = 2164.5021645022002
runRgoffset.inputs.down_spacing_prf2 = 2164.5021645022002
runRgoffset.inputs.family = estimateoffsets
runRgoffset.inputs.first_sample_across = 123
runRgoffset.inputs.first_sample_down = 123
runRgoffset.inputs.iscomplex_image1 = False
runRgoffset.inputs.iscomplex_image2 = False
runRgoffset.inputs.last_sample_across = 5121
runRgoffset.inputs.last_sample_down = 6310
runRgoffset.inputs.name = insarapp_intsim_estoffset
runRgoffset.inputs.number_windows_across = 80
runRgoffset.inputs.number_windows_down = 80
runRgoffset.inputs.oversampling_factor = 16
runRgoffset.inputs.search_window_size = 20
runRgoffset.inputs.window_size = 32
runRgoffset.inputs.zoom_window_size = 8
####################################################################################################
2022-01-14 22:41:39,620 - isce.insar.runRgoffset - INFO - 
####################################################################################################
    runRgoffset - Outputs
----------------------------------------------------------------------------------------------------
runRgoffset.outputs.LOCATION_ACROSS = catalog/runRgoffset.outputs.LOCATION_ACROSS.000
runRgoffset.outputs.LOCATION_ACROSS_OFFSET = catalog/runRgoffset.outputs.LOCATION_ACROSS_OFFSET.001
runRgoffset.outputs.LOCATION_DOWN = catalog/runRgoffset.outputs.LOCATION_DOWN.002
runRgoffset.outputs.LOCATION_DOWN_OFFSET = catalog/runRgoffset.outputs.LOCATION_DOWN_OFFSET.003
runRgoffset.outputs.SNR = catalog/runRgoffset.outputs.SNR.004
####################################################################################################
GDAL close: resampImage.amp.vrt
GDAL close: simamp.rdr.vrt
Dumping the application's pickle object _insar to file  PICKLE/rgoffset
The remaining steps are (in order):  ['rg_outliers2', 'resamp_only', 'settopoint2', 'correct', 'coherence', 'filter', 'mask', 'unwrap', 'unwrap2stage', 'geocode']
Running step rg_outliers2
2022-01-14 22:41:44,463 - isce.insar.runOffoutliers - INFO - Error limit = 100
2022-01-14 22:41:44,467 - isce.insar.runOffoutliers - INFO - Culling offset field outliers
2022-01-14 22:41:44,470 - isce.insar.runOffoutliers - INFO - Number of input offsets: 6400
2022-01-14 22:41:44,471 - isce.insar.runOffoutliers - INFO - Distance: 10.000000
2022-01-14 22:41:44,476 - isceobj.Location.OffsetField - INFO - 5744 offsets culled

 1-D calculation:

          Slope across  Intercept:
 Across:    1.22675381E-04 -0.126194537
 Down:      8.54811733E-05 -0.977508783

2022-01-14 22:41:44,478 - isce.insar.runOffoutliers - INFO - 
####################################################################################################
    runOffoutliers - Inputs
----------------------------------------------------------------------------------------------------
runOffoutliers.inputs.DISTANCE = 10.0
runOffoutliers.inputs.family = _family
runOffoutliers.inputs.metadata_location = 
runOffoutliers.inputs.name = _family_name
####################################################################################################
2022-01-14 22:41:44,479 - isce.insar.runOffoutliers - INFO - 
####################################################################################################
    runOffoutliers - Outputs
----------------------------------------------------------------------------------------------------
####################################################################################################
2022-01-14 22:41:44,571 - isce.insar.runOffoutliers - INFO - Number of offsets left after culling: 576
2022-01-14 22:41:44,572 - isce.insar.runOffoutliers - INFO - Error limit = 100
2022-01-14 22:41:44,572 - isce.insar.runOffoutliers - INFO - Culling offset field outliers
2022-01-14 22:41:44,572 - isce.insar.runOffoutliers - INFO - Number of input offsets: 576
2022-01-14 22:41:44,572 - isce.insar.runOffoutliers - INFO - Distance: 5.000000
2022-01-14 22:41:44,573 - isceobj.Location.OffsetField - INFO - 0 offsets culled

 1-D calculation:

          Slope across  Intercept:
 Across:    5.15227148E-04 -0.452301294
 Down:      4.78002417E-04  -3.04747891

2022-01-14 22:41:44,575 - isce.insar.runOffoutliers - INFO - 
####################################################################################################
    runOffoutliers - Inputs
----------------------------------------------------------------------------------------------------
runOffoutliers.inputs.DISTANCE = 5.0
runOffoutliers.inputs.family = _family
runOffoutliers.inputs.metadata_location = 
runOffoutliers.inputs.name = _family_name
####################################################################################################
2022-01-14 22:41:44,575 - isce.insar.runOffoutliers - INFO - 
####################################################################################################
    runOffoutliers - Outputs
----------------------------------------------------------------------------------------------------
####################################################################################################
2022-01-14 22:41:44,593 - isce.insar.runOffoutliers - INFO - Number of offsets left after culling: 98
2022-01-14 22:41:44,593 - isce.insar.runOffoutliers - ERROR - Small number of output Offsets after culling: 98 .
 Increase number of windows (or) window sizes (or) provide gross offset manually.
Traceback (most recent call last):
  File "/home/isce/isce/install/isce/applications/insarApp.py", line 1191, in <module>
    status = insar.run()
  File "/home/isce/isce/install/isce/components/iscesys/Component/Application.py", line 129, in run
    exitStatus = self._processSteps()
  File "/home/isce/isce/install/isce/components/iscesys/Component/Application.py", line 392, in _processSteps
    result = func(*pargs, **kwargs)
  File "/home/isce/isce/install/isce/applications/insarApp.py", line 898, in iterate_runOffoutliers
    list(map(self.runOffoutliers, iterator, erriterator))
  File "/home/isce/isce/install/isce/components/isceobj/InsarProc/Factories.py", line 53, in __call__
    return self.method(self.other, *args, **kwargs)
  File "/home/isce/isce/install/isce/components/isceobj/InsarProc/runOffoutliers.py", line 60, in runOffoutliers
    raise Exception('Offset estimation Failed.')
Exception: Offset estimation Failed.``

**Comment by gyp-1991-gq** [comment]
Can it be installed on Windows 10?

**Comment by durerimon** [comment]
I guess you can.

**Comment by EJFielding** [comment]
Hi @durerimon, the old  `insarApp.py` application is not supported since a few years ago. You should use the newer `stripmapApp.py` for processing ALOS data.
