### ISSUE TITLE
__init__.py   KeyError: 'formatters'

### ISSUE THREAD

**Issue by guangbaoshen** [isce-framework/isce2#450]
hi, after installing the ISCE v2.6.0，I met the error below, it shows that something wrong with the __init__.py file, is there anyone met the same error before? 

theone@noone:~$ python3
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import isce
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/theone/isce2/install/isce/__init__.py", line 39, in <module>
    _fc(os.path.join(isce_path, 'defaults', 'logging', 'logging.conf'))
  File "/usr/lib/python3.6/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python3.6/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
>>>

**Comment by guangbaoshen** [comment]
change the ISCE_2.6.0  to the ISCE_2.4.2, the problem solved, sorry for the interruption.

**Comment by priscillasterna** [comment]
Hi, I'm also getting the same error. From where did you get isce2.4 version.
Thanks in advance
