### ISSUE TITLE
running step denseoffsets：gdal_translate: not found, exception:32512 could not be executed

### ISSUE THREAD

**Issue by guangbaoshen** [isce-framework/isce2#451]
when i use isce_2.4.2  topsApp.py to do the denseoffsets step, an error comes out like below, is there anybody met the problem before?

theone@noone:~/AutoRIFT$ topsApp.py --dostep=denseoffsets
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
2022-02-26 12:35:52,781 - isce.insar - INFO - ISCE VERSION = 2.4.2, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20201116, CURRENT_SVN_REVISION = 
ISCE VERSION = 2.4.2, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20201116, CURRENT_SVN_REVISION = 
Step processing
Running step denseoffsets

============================================================
Configuring DenseAmpcor object for processing...

sh: 1: gdal_translate: not found
Traceback (most recent call last):
  File "/home/theone/isce3/install/isce/applications/topsApp.py", line 1041, in <module>
    insar.run()
  File "/home/theone/isce3/install/isce/components/iscesys/Component/Application.py", line 142, in run
    exitStatus = self._processSteps()
  File "/home/theone/isce3/install/isce/components/iscesys/Component/Application.py", line 405, in _processSteps
    result = func(*pargs, **kwargs)
  File "/home/theone/isce3/install/isce/components/isceobj/TopsProc/Factories.py", line 40, in __call__
    return self.method(self.other, *args, **kwargs)
  File "/home/theone/isce3/install/isce/components/isceobj/TopsProc/runDenseOffsets.py", line 28, in runDenseOffsets
    runDenseOffsetsCPU(self)
  File "/home/theone/isce3/install/isce/components/isceobj/Util/decorators.py", line 290, in use_api_decorator
    ret = func(*args,**kwargs)
  File "/home/theone/isce3/install/isce/components/isceobj/TopsProc/runDenseOffsets.py", line 61, in runDenseOffsetsCPU
    raise Exception('{0} could not be executed'.format(status))
Exception: 32512 could not be executed

**Comment by guangbaoshen** [comment]
the reason of the error is lack of the package of 'gdal_translate', i use the ubuntu18.04.01, use the command line:
sudo apt-get install gdal_bin
the error is fixed, sorry for the interruption.
