### ISSUE TITLE
db file doesnt exist - run_08_timeseries_misreg

### ISSUE THREAD

**Issue by jaha2600** [isce-framework/isce2#460]
I am running through the stackSentinel.py shell scripts having built files using the following command: 
`stackSentinel.py -s ./SLC/ -d ./DEM/dem.envi -a ./AuxDir/ -o orbits/ -b '6.389 6.701 2.200 3.405' -c 2`

I attach my conda envrionment .yml file (as [isce2.txt](https://github.com/isce-framework/isce2/files/8257057/isce2.txt)) and slc filelist [slc_list.txt](https://github.com/isce-framework/isce2/files/8257059/slc_list.txt).

Up until this morning I was receiving the error shown in #458 , so I have changed my python version to 3.9.10 (conda install -c conda-forge python=3.9.10). This now allows stage_07 to run correctly. However run_08 now fails out with the error shown below:

`./run_08_timeseries_misreg`
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Traceback (most recent call last):
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.10/site-packages/isce/contrib/stack/stripmapStack/invertMisreg.py", line 205, in <module>
    main()
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.10/site-packages/isce/contrib/stack/stripmapStack/invertMisreg.py", line 142, in main
    polyInfo = getPolyInfo(pairDirs[0])
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.10/site-packages/isce/contrib/stack/stripmapStack/invertMisreg.py", line 77, in getPolyInfo
    with shelve.open(os.path.join(filename,'misreg'),flag='r') as db:
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.9/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.9/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.9/dbm/__init__.py", line 85, in open
    raise error[0]("db file doesn't exist; "

dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Traceback (most recent call last):
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.10/site-packages/isce/contrib/stack/stripmapStack/invertMisreg.py", line 205, in <module>
    main()
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.10/site-packages/isce/contrib/stack/stripmapStack/invertMisreg.py", line 142, in main
    polyInfo = getPolyInfo(pairDirs[0])
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.10/site-packages/isce/contrib/stack/stripmapStack/invertMisreg.py", line 77, in getPolyInfo
    with shelve.open(os.path.join(filename,'misreg'),flag='r') as db:
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.9/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.9/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/home/jasmine/miniconda3/envs/isce2/lib/python3.9/dbm/__init__.py", line 85, in open
    raise error[0]("db file doesn't exist; "
dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db

**Comment by f2695443173** [comment]
May I ask if you have solved this problem? I have also encountered the same problem and am eager to know how you resolved it.

**Comment by xiangbenzhang** [comment]
May I ask if you have solved this problem? I have also encountered the same problem and am eager to know how you resolved it.

**Comment by mhmnia** [comment]
Check the paths where you export them. 
You can deactivate the stripmapStack address if you use Sentinel-1 ...

export PATH=~/...../isce2-main/contrib/stack/topsStack/:$PATH
#export PATH=~/...../isce2-main/contrib/stack/stripmapStack:$PATH
