### ISSUE TITLE
unwrap issue: list index out of range

### ISSUE THREAD

**Issue by totaibi** [isce-framework/isce2#477]
Hi folks,

I'm trying to process slc products using isce2 and got the following errors:

```
Running: mergeBursts
['--stack', '/net/kraken/nobak/thamer/tr116/Najran/stack', '--inp_reference', '/net/kraken/nobak/thamer/tr116/Najran/interferograms/20170324_20170429', '--dirname', '/net/kraken/nob
ak/thamer/tr116/Najran/interferograms/20170324_20170429', '--name_pattern', 'fine*int', '--outfile', '/net/kraken/nobak/thamer/tr116/Najran/merged/interferograms/20170324_20170429/f
ine.int', '--method', 'top', '--aligned', '--valid_only', '--use_virtual_files', '--multilook', '--range_looks', '9', '--azimuth_looks', '3']
Traceback (most recent call last):
  File "/home/thamer/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/thamer/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/thamer/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/thamer/isce2/contrib/stack/topsStack/mergeBursts.py", line 408, in main
    mergeBurstsVirtual(frames, referenceFrames, fileList, inps.outfile+suffix, validOnly=inps.validOnly)
  File "/home/thamer/isce2/contrib/stack/topsStack/mergeBursts.py", line 99, in mergeBurstsVirtual
    topSwath = min(refSwaths, key = lambda x: x.sensingStart)
ValueError: min() arg is an empty sequence
######################################################################################
Running: FilterAndCoherence
['--input', '/net/kraken/nobak/thamer/tr116/Najran/merged/interferograms/20170429_20170523/fine.int', '--filt', '/net/kraken/nobak/thamer/tr116/Najran/merged/interferograms/20170429
_20170523/filt_fine.int', '--coh', '/net/kraken/nobak/thamer/tr116/Najran/merged/interferograms/20170429_20170523/filt_fine.cor', '--strength', '0.5', '--slc1', '/net/kraken/nobak/t
hamer/tr116/Najran/merged/SLC/20170429/20170429.slc.full', '--slc2', '/net/kraken/nobak/thamer/tr116/Najran/merged/SLC/20170523/20170523.slc.full', '--complex_coh', '/net/kraken/nob
ak/thamer/tr116/Najran/merged/interferograms/20170429_20170523/fine.cor', '--range_looks', '9', '--azimuth_looks', '3']

2022-04-10 15:19:20,140 - isce.tops.runFilter - INFO - Applying power-spectral filter
Traceback (most recent call last):
  File "/home/thamer/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/thamer/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/thamer/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/thamer/isce2/contrib/stack/topsStack/FilterAndCoherence.py", line 192, in main
    runFilter(inps.infile, inps.filtfile, inps.filterstrength)
  File "/home/thamer/isce2/contrib/stack/topsStack/FilterAndCoherence.py", line 48, in runFilter
    intImage.load( infile + '.xml')
  File "/home/thamer/miniconda3/envs/isce2/lib/python3.8/site-packages/isce/components/iscesys/Component/Configurable.py", line 1407, in load
    tmpProp, tmpFact, tmpMisc = FP.parse(filename)
  File "/home/thamer/miniconda3/envs/isce2/lib/python3.8/site-packages/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse
    root = ET.parse(filename)
  File "/home/thamer/miniconda3/envs/isce2/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/home/thamer/miniconda3/envs/isce2/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/net/kraken/nobak/thamer/tr116/Najran/merged/interferograms/20170429_20170604/fine.int.xml'
######################################################################################
Running: unwrap
['--ifg', '/net/kraken/nobak/thamer/tr116/Najran/merged/interferograms/20220121_20220202/filt_fine.int', '--unw', '/net/kraken/nobak/thamer/tr116/Najran/merged/interferograms/20220121_20220202/filt_fine.unw', '--coh', '/net/kraken/nobak/thamer/tr116/Najran/merged/interferograms/20220121_20220202/filt_fine.cor', '--reference', '/net/kraken/nobak/thamer/tr116/Najran/reference', '--defomax', '2', '--rlks', '9', '--alks', '3', '--method', 'snaphu']
unwrapping method :  snaphu
Traceback (most recent call last):
  File "/home/thamer/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
Completed Parsing the Configuration file
Functions to be executed:
['Function-1']
    main(args.start,args.end)
  File "/home/thamer/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/thamer/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/thamer/isce2/contrib/stack/topsStack/unwrap.py", line 338, in main
    xmlFile = os.path.join(inps.reference , 'IW{0}.xml'.format(swathList[0]))
IndexError: list index out of range
```

Any suggestions?

Thanks in advance!

**Comment by totaibi** [comment]
Hi Jasmine

Unfortunately I could not resolve it. I decided to shift into GMTStar

Good luck!
