### ISSUE TITLE
ALOS1 Leve1.1 run_03_geo2rdr_coarseResamp

### ISSUE THREAD

**Issue by pikaqiu202201** [isce-framework/isce2#480]
Hi,
Does anyone know how to solve this issue?
Error occurs when I process Alos-1 data in SLC format (FBD L1.1 from ASF).

stackStripMap.py -s /home/insar/1/Proc_2/Raw/SS/SLC_new -w /home/insar/1/SS/1/proc -d /home/insar/1/SS/1/dem -z --nofocus -W ionosphere -S 'ALOS'

run_3_geo2rdr_coarseResamp step

Running: geo2rdr
['--reference', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070609', '--secondary', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070725', '--geom', '/home/insar/1/SS/1/proc/merged/geom_reference', '--native', '--outdir', '/home/insar/1/SS/1/proc/offsets/20070725']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
/home/insar/1/Proc_2/Raw/SS/SLC_new/20070725
CPU mode
/home/insar/1/Proc_2/Raw/SS/SLC_new/20070725/data
07-25 19:43:07.202000
2159.8272138229
849864.342658335
Zero doppler
Turning off bistatic delay correction term by default.
Running: resampleSlc
['--reference', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070609', '--secondary', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070725', '--coreg', '/home/insar/1/SS/1/proc/coregSLC/Coarse/20070725', '--offsets', '/home/insar/1/SS/1/proc/offsets/20070725']
cp /home/insar/1/Proc_2/Raw/SS/SLC_new/20070725/data* /home/insar/1/SS/1/proc/coregSLC/Coarse/20070725/secondaryShelve
Polynomial doppler provided
List of coefficients provided
Traceback (most recent call last):
File "/opt/isce2/isce/contrib/stack/stripmapStack/resampleSlc.py", line 118, in resampSecondary
coeffs = [factor * 2np.pival/prf for val in doppler._coeffs]

**Comment by vittorio3d** [comment]
Hello! I have the same problem... you  solved?

**Comment by saeedmhanna1** [comment]
Hello, 

Any progress with this issue? I am having the same error!! 

Thanks,

**Comment by keepfighting666** [comment]
> Hi, Does anyone know how to solve this issue? Error occurs when I process Alos-1 data in SLC format (FBD L1.1 from ASF).
> 
> stackStripMap.py -s /home/insar/1/Proc_2/Raw/SS/SLC_new -w /home/insar/1/SS/1/proc -d /home/insar/1/SS/1/dem -z --nofocus -W ionosphere -S 'ALOS'
> 
> run_3_geo2rdr_coarseResamp step
> 
> Running: geo2rdr ['--reference', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070609', '--secondary', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070725', '--geom', '/home/insar/1/SS/1/proc/merged/geom_reference', '--native', '--outdir', '/home/insar/1/SS/1/proc/offsets/20070725'] This is the Open Source version of ISCE. Some of the workflows depend on a separate licensed package. To obtain the licensed package, please make a request for ISCE through the website: https://download.jpl.nasa.gov/ops/request/index.cfm. Alternatively, if you are a member, or can become a member of WinSAR you may be able to obtain access to a version of the licensed sofware at https://winsar.unavco.org/software/isce /home/insar/1/Proc_2/Raw/SS/SLC_new/20070725 CPU mode /home/insar/1/Proc_2/Raw/SS/SLC_new/20070725/data 07-25 19:43:07.202000 2159.8272138229 849864.342658335 Zero doppler Turning off bistatic delay correction term by default. Running: resampleSlc ['--reference', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070609', '--secondary', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070725', '--coreg', '/home/insar/1/SS/1/proc/coregSLC/Coarse/20070725', '--offsets', '/home/insar/1/SS/1/proc/offsets/20070725'] cp /home/insar/1/Proc_2/Raw/SS/SLC_new/20070725/data* /home/insar/1/SS/1/proc/coregSLC/Coarse/20070725/secondaryShelve Polynomial doppler provided List of coefficients provided Traceback (most recent call last): File "/opt/isce2/isce/contrib/stack/stripmapStack/resampleSlc.py", line 118, in resampSecondary coeffs = [factor * 2np.pival/prf for val in doppler._coeffs]

Hello! I’m processing ALOS PALSAR data for the first time and I’m a bit unsure about the correct workflow. I’ve downloaded Level 1.1 data—could you share the key steps or commands needed to process it? Any guidance would be greatly appreciated. Thank you!
![image](https://github.com/user-attachments/assets/7673ad15-364d-42fe-a11f-eb5961e0abd4)

**Comment by gangjizetian** [comment]
> Hello,
> 
> Any progress with this issue? I am having the same error!!
> 
> Thanks,

May I ask if this issue has been resolved? Looking forward to your reply

**Comment by gangjizetian** [comment]
> Hello! I have the same problem... you solved?

May I ask if this issue has been resolved? Looking forward to your reply

**Comment by gangjizetian** [comment]
> Hi, Does anyone know how to solve this issue? Error occurs when I process Alos-1 data in SLC format (FBD L1.1 from ASF).
> 
> stackStripMap.py -s /home/insar/1/Proc_2/Raw/SS/SLC_new -w /home/insar/1/SS/1/proc -d /home/insar/1/SS/1/dem -z --nofocus -W ionosphere -S 'ALOS'
> 
> run_3_geo2rdr_coarseResamp step
> 
> Running: geo2rdr ['--reference', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070609', '--secondary', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070725', '--geom', '/home/insar/1/SS/1/proc/merged/geom_reference', '--native', '--outdir', '/home/insar/1/SS/1/proc/offsets/20070725'] This is the Open Source version of ISCE. Some of the workflows depend on a separate licensed package. To obtain the licensed package, please make a request for ISCE through the website: https://download.jpl.nasa.gov/ops/request/index.cfm. Alternatively, if you are a member, or can become a member of WinSAR you may be able to obtain access to a version of the licensed sofware at https://winsar.unavco.org/software/isce /home/insar/1/Proc_2/Raw/SS/SLC_new/20070725 CPU mode /home/insar/1/Proc_2/Raw/SS/SLC_new/20070725/data 07-25 19:43:07.202000 2159.8272138229 849864.342658335 Zero doppler Turning off bistatic delay correction term by default. Running: resampleSlc ['--reference', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070609', '--secondary', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070725', '--coreg', '/home/insar/1/SS/1/proc/coregSLC/Coarse/20070725', '--offsets', '/home/insar/1/SS/1/proc/offsets/20070725'] cp /home/insar/1/Proc_2/Raw/SS/SLC_new/20070725/data* /home/insar/1/SS/1/proc/coregSLC/Coarse/20070725/secondaryShelve Polynomial doppler provided List of coefficients provided Traceback (most recent call last): File "/opt/isce2/isce/contrib/stack/stripmapStack/resampleSlc.py", line 118, in resampSecondary coeffs = [factor * 2np.pival/prf for val in doppler._coeffs]

May I ask if this issue has been resolved? Looking forward to your reply

**Comment by keepfighting666** [comment]
> > Hi, Does anyone know how to solve this issue? Error occurs when I process Alos-1 data in SLC format (FBD L1.1 from ASF).
> > stackStripMap.py -s /home/insar/1/Proc_2/Raw/SS/SLC_new -w /home/insar/1/SS/1/proc -d /home/insar/1/SS/1/dem -z --nofocus -W ionosphere -S 'ALOS'
> > run_3_geo2rdr_coarseResamp step
> > Running: geo2rdr ['--reference', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070609', '--secondary', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070725', '--geom', '/home/insar/1/SS/1/proc/merged/geom_reference', '--native', '--outdir', '/home/insar/1/SS/1/proc/offsets/20070725'] This is the Open Source version of ISCE. Some of the workflows depend on a separate licensed package. To obtain the licensed package, please make a request for ISCE through the website: https://download.jpl.nasa.gov/ops/request/index.cfm. Alternatively, if you are a member, or can become a member of WinSAR you may be able to obtain access to a version of the licensed sofware at https://winsar.unavco.org/software/isce /home/insar/1/Proc_2/Raw/SS/SLC_new/20070725 CPU mode /home/insar/1/Proc_2/Raw/SS/SLC_new/20070725/data 07-25 19:43:07.202000 2159.8272138229 849864.342658335 Zero doppler Turning off bistatic delay correction term by default. Running: resampleSlc ['--reference', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070609', '--secondary', '/home/insar/1/Proc_2/Raw/SS/SLC_new/20070725', '--coreg', '/home/insar/1/SS/1/proc/coregSLC/Coarse/20070725', '--offsets', '/home/insar/1/SS/1/proc/offsets/20070725'] cp /home/insar/1/Proc_2/Raw/SS/SLC_new/20070725/data* /home/insar/1/SS/1/proc/coregSLC/Coarse/20070725/secondaryShelve Polynomial doppler provided List of coefficients provided Traceback (most recent call last): File "/opt/isce2/isce/contrib/stack/stripmapStack/resampleSlc.py", line 118, in resampSecondary coeffs = [factor * 2np.pival/prf for val in doppler._coeffs]
> 
> May I ask if this issue has been resolved? Looking forward to your reply

hello, have you solved it? I need your help.
