### ISSUE TITLE
TopsApp error

### ISSUE THREAD

**Issue by hafsaaeman** [isce-framework/isce2#535]
### Discussed in https://github.com/isce-framework/isce2/discussions/
Hi ISCE team, 
I am trying to perform DInSAR of two Sentinel-1 IW SLC data. I installed ISCE using the conda-forge. 
I am unable to follow the error saying Could not extract swath 1 and No annotation XML found inside the SAFE/ zip file. I am able to find the XML files as shown below. Although I have added the polarization property as followed by previous discussion #495 but I could not resolve this issue
```
.SAFE annotation directory contains following files /home/dev/Sarah_Dataisce/slc_dir/S1B_IW_SLC__1SDV_20200517T135026_20200517T135056_021622_0290CB_99E2.SAFE/annotation
rfi
s1b-iw1-slc-vh-20200517t135026-20200517t135054-021622-0290cb-001.xml
s1b-iw1-slc-vv-20200517t135026-20200517t135054-021622-0290cb-004.xml
s1b-iw2-slc-vh-20200517t135027-20200517t135055-021622-0290cb-002.xml
s1b-iw2-slc-vv-20200517t135027-20200517t135055-021622-0290cb-005.xml
s1b-iw3-slc-vh-20200517t135028-20200517t135056-021622-0290cb-003.xml
s1b-iw3-slc-vv-20200517t135028-20200517t135056-021622-0290cb-006.xml

my input files are:
topsApp.xml
<topsApp>
  <component name="topsinsar">
    <property name="Sensor name">SENTINEL1</property>
    <component name="reference">
        <catalog>reference.xml</catalog>
    </component>
    <component name="secondary">
        <catalog>secondary.xml</catalog>
    </component>
    <property name="swaths">[1]</property>
    <!-- <property name="range looks">7</property> -->
    <!-- <property name="azimuth looks">3</property> -->
    <!-- <property name="region of interest">[37.98, 38.33, -118.21, -117.68]</property> -->
    <property name="do unwrap">True</property>
    <property name="unwrapper name">snaphu_mcf</property>
    <property name="do denseoffsets">True</property>
  </component>
</topsApp>


reference.xml
<component name="reference">
    <property name="orbit directory">/home/dev/Sarah_Dataisce/localorb</property>
    <property name="output directory">reference</property>
    <property name="polarization">'vh'</property>
    <property name="safe">/home/dev/Sarah_Dataisce/slc_dir/S1A_IW_SLC__1SDV_20200511T135117_20200511T135144_032518_03C421_7768.SAFE</property>
</component>

secondary.xml
<component name="secondary">
    <property name="orbit directory">/home/dev/Sarah_Dataisce/localorb</property>
    <property name="output directory">secondary</property>
    <property name="polarization">'vh'</property>
    <property name="safe">/home/dev/Sarah_Dataisce/slc_dir/S1B_IW_SLC__1SDV_20200517T135026_20200517T135056_021622_0290CB_99E2.SAFE</property>
</component>


Below is the error message and the XML file is attached at the bottom. Kindly have a look at this error. 

(tf_gpu) dev@dev-Vostro-3500:~/ISCE_processing/Inputfiles$ /home/dev/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/isce/applications/topsApp.py topsApp.xml 
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
2022-07-21 11:03:52,454 - isce.insar - INFO - ISCE VERSION = 2.4.2, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20201116, CURRENT_SVN_REVISION = 
ISCE VERSION = 2.4.2, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20201116, CURRENT_SVN_REVISION = 
None
The currently supported sensors are:  ['SENTINEL1']
Input XML files:  ['/home/dev/Sarah_Dataisce/slc_dir/S1A_IW_SLC__1SDV_20200511T135117_20200511T135144_032518_03C421_7768.SAFE/annotation/s1a-iw1-slc-vh-20200511t135119-20200511t135144-032518-03c421-001.xml']
Input TIFF files:  ['/home/dev/Sarah_Dataisce/slc_dir/S1A_IW_SLC__1SDV_20200511T135117_20200511T135144_032518_03C421_7768.SAFE/measurement/s1a-iw1-slc-vh-20200511t135119-20200511t135144-032518-03c421-001.tiff']
Manifest files:  ['/home/dev/Sarah_Dataisce/slc_dir/S1A_IW_SLC__1SDV_20200511T135117_20200511T135144_032518_03C421_7768.SAFE/manifest.safe']
Setting IPF version to :  003.20
Could not extract swath 1 from ['/home/dev/Sarah_Dataisce/slc_dir/S1A_IW_SLC__1SDV_20200511T135117_20200511T135144_032518_03C421_7768.SAFE']
Generated error:  'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
Input XML files:  ['/home/dev/Sarah_Dataisce/slc_dir/S1B_IW_SLC__1SDV_20200517T135026_20200517T135056_021622_0290CB_99E2.SAFE/annotation/s1b-iw1-slc-vh-20200517t135026-20200517t135054-021622-0290cb-001.xml']
Input TIFF files:  ['/home/dev/Sarah_Dataisce/slc_dir/S1B_IW_SLC__1SDV_20200517T135026_20200517T135056_021622_0290CB_99E2.SAFE/measurement/s1b-iw1-slc-vh-20200517t135026-20200517t135054-021622-0290cb-001.tiff']
Manifest files:  ['/home/dev/Sarah_Dataisce/slc_dir/S1B_IW_SLC__1SDV_20200517T135026_20200517T135056_021622_0290CB_99E2.SAFE/manifest.safe']
Setting IPF version to :  003.20
Could not extract swath 1 from ['/home/dev/Sarah_Dataisce/slc_dir/S1B_IW_SLC__1SDV_20200517T135026_20200517T135056_021622_0290CB_99E2.SAFE']
Generated error:  'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
2022-07-21 11:03:52,669 - isce.topsinsar.runPreprocessor - INFO - 
####################################################################################################
    runPreprocessor
----------------------------------------------------------------------------------------------------
common.Input list of swaths to process:  = [1]
####################################################################################################
Skipping processing for swath number IW-1
No swaths contain any burst overlaps ... cannot continue for interferometry applications
2022-07-21 11:03:52,669 - isce.topsinsar.runPreprocessor - INFO - 
####################################################################################################
    runComputeBaseline
----------------------------------------------------------------------------------------------------
####################################################################################################
Traceback (most recent call last):
  File "/home/dev/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/isce/applications/topsApp.py", line 1041, in <module>
    insar.run()
  File "/home/dev/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/isce/components/iscesys/Component/Application.py", line 144, in run
    exitStatus = self.main()
  File "/home/dev/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/isce/applications/topsApp.py", line 960, in main
    self.verifyDEM()
  File "/home/dev/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/isce/components/isceobj/TopsProc/Factories.py", line 40, in __call__
    return self.method(self.other, *args, **kwargs)
  File "/home/dev/anaconda3/envs/tf_gpu/lib/python3.9/site-packages/isce/components/isceobj/TopsProc/runVerifyDEM.py", line 75, in runVerifyDEM
    raise Exception('Something went wrong in determining bboxes')
Exception: Something went wrong in determining bboxes

Thank you in advance

**Comment by piyushrpt** [comment]
You appear to be using a really old version of isce2 - 2.4.2. Please update to use the latest version

**Comment by hafsaaeman** [comment]
thank you! I did with updated version. it worked!

**Comment by alejobeap** [comment]
Hi I have the same problem 
![image](https://user-images.githubusercontent.com/65787135/210118769-60ca5606-7a8f-441f-907a-81e490458da1.png)

is possible to help me

Thanks.

Alejo

**Comment by 17797112023** [comment]
1

**Comment by 17797112023** [comment]
I seem to have encountered such a problem, whether you did not unzip the SLC file

**Comment by ukmkkpk** [comment]
I have the same question and my question's details in https://github.com/isce-framework/isce2/issues/779, if anyone can help me I would be very grateful .
