### ISSUE TITLE
run_20 ion issue even with no pairs in pairs_diff_starting_ranges.txt

### ISSUE THREAD

**Issue by jaha2600** [isce-framework/isce2#551]
I am currently trying to run the ionospheric  correction module on some Sentinel-1 images over Greenland. 
There are no files in pairs_diff_starting_ranges.txt so I do not remove any files from processing.

I have completed the #500 update to account for the incorrect indentation, but this did not result in any changes in the output error, this may also link to  #511 

Below are my `s1_select_ion.py` and `stackSentinel.py` commands (i am using the default ion_param.txt file).
`s1_select_ion.py -dir ./slc -sn 67.122314/69.035088 -nr 10`

`stackSentinel.py -s slc/ -d dem/glo_30.dem.wgs84 -a aux_dir/ -o orbits/ -b '67.122314 69.035088 -54.830711 -48.040665' -c 4 -p hh --param_ion ./ion_param.txt --num_connections_ion 3 --num_proc4topo 10.`
From run_20 onwards I get failures and missing files in all subsequent stages. This results in run_24 failing completely.  It is unclear to me where all the failures are coming from given the empty pairs_diff_starting_ranges.txt file.
Below is the run_20 error. I have also attached the full run_19, run_20 and run_24 output files and can provide more if required.

Any help would be greatly appreciated. 

Running: unwrap
['--ifg', '/gpfs/summit/scratch/jaha2600/GREENLAND/2022/stack_mintpy/kanger_25_365/ion/20180730_20190526/lower/merged/fine.int', '--unw', '/gpfs/summit/scratch/jaha2600/GREENLAND/2022/stack_mintpy/kanger_25_365/ion/20180730_20190526/lower/merged/fine.unw', '--coh', '/gpfs/summit/scratch/jaha2600/GREENLAND/2022/stack_mintpy/kanger_25_365/ion/20180730_20190526/lower/merged/fine.cor', '--reference', '/gpfs/summit/scratch/jaha2600/GREENLAND/2022/stack_mintpy/kanger_25_365/reference', '--defomax', '2', '--rlks', '40', '--alks', '10', '--method', 'snaphu']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
unwrapping method :  snaphu
Traceback (most recent call last):
  File "/projects/jaha2600/software/anaconda/isce2_summit/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/projects/jaha2600/software/anaconda/isce2_summit/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/projects/jaha2600/software/anaconda/isce2_summit/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/projects/jaha2600/software/anaconda/isce2_summit/contrib/stack/topsStack/unwrap.py", line 328, in main
    fncall(inps.intfile, inps.unwfile, inps.cohfile, metadata, defomax=inps.defomax)
  File "/projects/jaha2600/software/anaconda/isce2_summit/contrib/stack/topsStack/unwrap.py", line 237, in runUnwrapMcf
    runUnwrap(infile, outfile, corfile, config, costMode = 'SMOOTH',initMethod = 'MCF', defomax = defomax, initOnly = True)
  File "/projects/jaha2600/software/anaconda/isce2_summit/contrib/stack/topsStack/unwrap.py", line 170, in runUnwrap
    img.load(infile + '.xml')
  File "/projects/jaha2600/software/anaconda/isce2_summit/local/packages/isce/components/iscesys/Component/Configurable.py", line 1407, in load
    tmpProp, tmpFact, tmpMisc = FP.parse(filename)
  File "/projects/jaha2600/software/anaconda/isce2_summit/local/packages/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse
    root = ET.parse(filename)
  File "/projects/jaha2600/software/anaconda/envs/isce2/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/projects/jaha2600/software/anaconda/envs/isce2/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/summit/scratch/jaha2600/GREENLAND/2022/stack_mintpy/kanger_25_365/ion/20180730_20190526/lower/merged/fine.int.xml'

[run_19_mergeBurstsIon_output_11164689.txt](https://github.com/isce-framework/isce2/files/9277735/run_19_mergeBurstsIon_output_11164689.txt)
[run_20_unwrap_ion_output_11164690.txt](https://github.com/isce-framework/isce2/files/9277737/run_20_unwrap_ion_output_11164690.txt)
[run_24_invertIon_output_11164694.txt](https://github.com/isce-framework/isce2/files/9277738/run_24_invertIon_output_11164694.txt)

**Comment by jaha2600** [comment]
I have reopened this because these errors have returned.
I have ensured that the bounds are appropriate for use with the ion run, and have run s1_select_ion.py multiple times.
