### ISSUE TITLE
module overlap_withDEM not found

### ISSUE THREAD

**Issue by liveeo-nicolas-garcia** [isce-framework/isce2#564]
Greetings!

I am running into this issue. I want to execute the `run_07_pairs_misreg ` step from the `stackSentinel.py` routine and I get the following:
```
Completed Parsing the Configuration file
Functions to be executed:
['Function-1', 'Function-2', 'Function-3', 'Function-4']
Running: generateIgram
['--reference', '/home/nicolas/Data/test_isce2_tops/reference', '--secondary', '/home/nicolas/Data/test_isce2_tops/coreg_secondarys/20210923', '--interferogram', '/home/nicolas/Data/test_isce2_tops/coarse_interferograms/20210911_20210923', '--interferogram_prefix', 'int', '--overlap']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
minSecondary,maxSecondary 1 3
minReference,maxReference 1 3
minBurst, maxBurst:  1 3
matching burst numbers:  1 1
multiply
read
No range offsets provided
rdict:  {'rangeOff1': '/home/nicolas/Data/test_isce2_tops/reference/overlap/IW1/range_bot_01_02.off', 'rangeOff2': '/home/nicolas/Data/test_isce2_tops/coreg_secondarys/20210923/overlap/IW1/range_bot_01_02.off', 'azimuthOff': '/home/nicolas/Data/test_isce2_tops/coreg_secondarys/20210923/overlap/IW1/azimuth_bot_01_02.off'}
multiply
read
No range offsets provided
matching burst numbers:  2 2
multiply
read
No range offsets provided
rdict:  {'rangeOff1': '/home/nicolas/Data/test_isce2_tops/reference/overlap/IW1/range_bot_02_03.off', 'rangeOff2': '/home/nicolas/Data/test_isce2_tops/coreg_secondarys/20210923/overlap/IW1/range_bot_02_03.off', 'azimuthOff': '/home/nicolas/Data/test_isce2_tops/coreg_secondarys/20210923/overlap/IW1/azimuth_bot_02_03.off'}
multiply
read
No range offsets provided
matching burst numbers:  3 3
multiply
read
No range offsets provided
rdict:  {'rangeOff1': '/home/nicolas/Data/test_isce2_tops/reference/overlap/IW1/range_bot_03_04.off', 'rangeOff2': '/home/nicolas/Data/test_isce2_tops/coreg_secondarys/20210923/overlap/IW1/range_bot_03_04.off', 'azimuthOff': '/home/nicolas/Data/test_isce2_tops/coreg_secondarys/20210923/overlap/IW1/azimuth_bot_03_04.off'}
multiply
read
No range offsets provided
Type:  <class 'isceobj.Sensor.TOPS.TOPSSwathSLCProduct.TOPSSwathSLCProduct'>
<isceobj.Sensor.TOPS.TOPSSwathSLCProduct.TOPSSwathSLCProduct object at 0x7f5b23b9eeb0>
Running: overlap_withDEM
['--interferogram', '/home/nicolas/Data/test_isce2_tops/coarse_interferograms/20210911_20210923', '--reference_dir', '/home/nicolas/Data/test_isce2_tops/reference', '--secondary_dir', '/home/nicolas/Data/test_isce2_tops/coreg_secondarys/20210923', '--overlap_dir', '/home/nicolas/Data/test_isce2_tops/ESD/20210911_20210923']
module overlap_withDEM not found
Traceback (most recent call last):
  File "/home/nicolas/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/nicolas/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/nicolas/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
AttributeError: 'NoneType' object has no attribute 'main'
```
I see that the overlap_withDEM module is not found, in any case this module just like all others are in the topsStack directory that is of course also added to the $PATH.

The repository I have here is updated and I installed isce=2.6.0 with conda in this env

Please let me know what else can I add as information
Thanks in advance

**Comment by liveeo-nicolas-garcia** [comment]
Solved by installing gcc with conda
