### ISSUE TITLE
Problem with run_07_pairs_misreg

### ISSUE THREAD

**Issue by javjrg** [isce-framework/isce2#647]
Hello everyone,

I'm having a problem with run 07 of stackSentinel. When I tried to run I have the following error.

`sh: looks.py: command not found
Traceback (most recent call last):
  File "/home/labgeo02/tools/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/labgeo02/tools/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/labgeo02/tools/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/labgeo02/tools/isce2/contrib/stack/topsStack/overlap_withDEM.py", line 354, in main
    multIntName= multilook(intName, alks = inps.esdAzimuthLooks, rlks=inps.esdRangeLooks)
  File "/home/labgeo02/tools/isce2/contrib/stack/topsStack/overlap_withDEM.py", line 50, in multilook
    raise Exception('Failed to multilook %s'%(intName))
Exception: Failed to multilook /home/labgeo02/clemun/Prueba_OLM_ROB_2021/stackproc/ESD/20211222_20211228/IW2/overlap_01.int
`

Could someone help me with this?

thanks

**Comment by javjrg** [comment]
I saw that in line 46 in `overlap_withDEM.py`, the script calls the routine `looks.py` and that doesn't exist.

The solution I did was to change the name of `looks_withDEM.py` to `looks.py`. I don't know if it's the official way but it works.

**Comment by alnguyen01** [comment]
> I saw that in line 46 in `overlap_withDEM.py`, the script calls the routine `looks.py` and that doesn't exist.
> 
> The solution I did was to change the name of `looks_withDEM.py` to `looks.py`. I don't know if it's the official way but it works.

I'm not sure if this bug was fixed (happened in release version 2.6.4 as well), but I experienced the same issue and was able to fix this by changing looks.py in overlap_withDEM.py in line 46 to looks_withDEM.py.
