### ISSUE TITLE
Erorr after run ./run_05_fullBurst_resample 

### ISSUE THREAD

**Issue by InSAR2023** [isce-framework/isce2#660]
Completed Parsing the Configuration file
Functions to be executed:
['Function-1']
Running: resamp_withCarrier
['--secondary', '/media/ahmed/easythree/Data/secondarys/20210218', '--reference', '/media/ahmed/easythree/Data/reference', '--coregdir', '/media/ahmed/easythree/Data/coreg_secondarys/20210218', '--azimuth_misreg', '/media/ahmed/easythree/Data/misreg/azimuth/dates/20210218.txt', '--range_misreg', '/media/ahmed/easythree/Data/misreg/range/dates/20210218.txt']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Estimated burst offset:  0
Shifts:  {0: 0, 1: 0, 2: -1, 3: 0}
Polynomial Order: 0 - by - 0 
0	
Polynomial Order: 0 - by - 0 
0	
Traceback (most recent call last):
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/ahmed/tools_insar/proc_insar/isce2/contrib/stack/topsStack/resamp_withCarrier.py", line 259, in main
    azCarrPoly, dpoly = secondary.estimateAzimuthCarrierPolynomials(slvBurst, offset = -1.0 * offset)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.10/site-packages/isce/components/isceobj/Sensor/TOPS/TOPSSwathSLCProduct.py", line 285, in estimateAzimuthCarrierPolynomials
    x = np.arange(0, burst.numberOfSamples,xstep,dtype=np.int)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?

**Comment by yuankailiu** [comment]
Hi @rtburns-jpl and @InSAR2023,

I am using the latest source code (with #639). I got the same thing in `run_01_unpack_topo_reference` inside `Sentinel1.py` [here](https://github.com/isce-framework/isce2/blob/038c04d5b904d29de1fa8e82cc7ddcc2e25b84d1/components/isceobj/Sensor/TOPS/Sentinel1.py#L493)

Although #639 fix the `np.complex`, the rest of the deprecated aliases are still there. Like `np.int` in [several places](https://github.com/isce-framework/isce2/search?q=np.int). 

#649 shows a temporary workaround to downgrade the numpy to 1.23.

**Comment by rtburns-jpl** [comment]
I think you can just replace `np.int` with `int` anywhere it's used. I'll issue a PR to do this treewide.

**Comment by InSAR2023** [comment]
After run below codes, it's works.

python -m pip uninstall numpy
python -m pip install numpy==1.23.1

**Comment by InSAR2023** [comment]
After installing version 1.23, I get the following error:

******************** step - load_data ********************
load_data.py --template /media/ahmed/easythree/EZ-InSAR/stackmintpy/smallbaselineApp.cfg /media/ahmed/easythree/EZ-InSAR/stackmintpy/mintpyfullparametersSenAT165.cfg --project mintpyfullparametersSenAT165
processor : isce
SAR platform/sensor : Sen

prepare metadata files for isce products
prep_isce.py -m /media/ahmed/easythree/EZ-InSAR/reference/IW1.xml -g /media/ahmed/easythree/EZ-InSAR/merged/geom_reference -b /media/ahmed/easythree/EZ-InSAR/baselines -f "/media/ahmed/easythree/EZ-InSAR/merged/interferograms//filt.unw" --geom-files hgt.rdr lat.rdr lon.rdr los.rdr los.rdr shadowMask.rdr waterMask.rdr
['/media/ahmed/easythree/EZ-InSAR/reference/data.rsc'] exists and is newer than ['/media/ahmed/easythree/EZ-InSAR/reference/IW1.xml'] --> skip.
preparing RSC file for geometry files
read perp baseline time-series from /media/ahmed/easythree/EZ-InSAR/baselines
preparing RSC file for: /media/ahmed/easythree/EZ-InSAR/merged/interferograms//filt.unw
[==> 6% ] 20200107_20200119 1/18 0s / 0s
[=====> 11% ] 20200107_20200131 2/18 0s / 0s
[=======> 17% ] 20200107_20200212 3/18 0s / 0s
[==========> 22% ] 20200119_20200131 4/18 0s / 0s
[=============> 28% ] 20200119_20200212 5/18 0s / 0s
[===============> 33% ] 20200119_20200224 6/18 0s / 0s
[===================> 39% ] 20200131_20200212 7/18 0s / 0s
[=====================> 44% ] 20200131_20200224 8/18 0s / 0s
[======================= 50% ] 20200131_20200307 9/18 0s / 0s
[======================= 56% ] 20200212_20200224 10/18 0s / 0s
[======================= 61% => ] 20200212_20200307 11/18 0s / 0s
[======================= 67% =====> ] 20200212_20200319 12/18 0s / 0s
[======================= 72% =======> ] 20200224_20200307 13/18 0s / 0s
[======================= 78% ==========> ] 20200224_20200319 14/18 0s / 0s
[======================= 83% =============> ] 20200224_20200331 15/18 0s / 0s
[======================= 89% ===============> ] 20200307_20200319 16/18 0s / 0s
[======================= 94% ==================> ] 20200307_20200331 17/18 0s / 0s
[==================================================] 20200319_20200331 18/18
Done.

updateMode : True
compression: None
multilook x/ystep: 1/1
multilook method : nearest
/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/numpy/core/_methods.py:182: RuntimeWarning: invalid value encountered in divide
ret = um.true_divide(
Traceback (most recent call last):
File "/home/ahmed/anaconda3/envs/InSARenv/bin/smallbaselineApp.py", line 10, in
sys.exit(main())
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/cli/smallbaselineApp.py", line 208, in main
run_smallbaselineApp(inps)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 1117, in run_smallbaselineApp
app.run(steps=inps.runSteps)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 874, in run
self.run_load_data(sname)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 176, in run_load_data
mintpy.cli.load_data.main(iargs)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/cli/load_data.py", line 123, in main
load_data(inps)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/load_data.py", line 800, in load_data
iDict = read_subset_box(iDict)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/load_data.py", line 200, in read_subset_box
pix_box = coord.bbox_geo2radar(geo_box)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/objects/coord.py", line 450, in bbox_geo2radar
y, x, y_res, x_res = self.geo2radar(lat, lon, print_msg=print_msg)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/objects/coord.py", line 314, in geo2radar
az[i], rg[i] = self._get_lookup_row_col(
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/objects/coord.py", line 187, in _get_lookup_row_col
raise RuntimeError(f'No coresponding coordinate found for y/x: {y}/{x}')
RuntimeError: No coresponding coordinate found for y/x: 30.2994/-91.3913

System information

    Operating system: Linux-Ubuntu (20.04)
    Python environment: conda (anaconda3)
    MintPy version: 1.5.1
