### ISSUE TITLE
Error after make_single_reference_stack_isce

### ISSUE THREAD

**Issue by InSAR2023** [isce-framework/isce2#679]
make_single_reference_stack_isce
make_single_reference_stack_isce David Bekaert, April 2017
 

-------------------------------
Stack path is: /media/Data/SARImages/Sarab/merged/merged/SLC/
SLC has a suffix as: .full
Geometry files have a suffix as: .full
SM: Reference Date = 20191203
-------------------------------

ln: No match.
rm: cannot remove '20191203.slc.full.vrt': No such file or directory
ERROR 4: 20191203.slc.full: No such file or directory
rm: cannot remove '20191203.slc.full.xml': No such file or directory
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Traceback (most recent call last):
  File "/home/mconda/miniconda3/envs/InSARenv/lib/python3.8/site-packages/isce/applications/gdal2isce_xml.py", line 137, in <module>
    raise Exception('Input file is not found ....')
Exception: Input file is not found ....
xml file for the SLC does not exist, you need to have these

**Comment by xiangbenzhang** [comment]
请问解决了吗？

**Comment by xiangbenzhang** [comment]
I am new of ISCE;when I use make_single_master_stack_isce to take isce to StaMPS,but I meet a problem,it is this 
（我是个最近才接触isce的新手，最近在通过isce2 to stamps进行时序insar时出现了问题，主要是运行make_single_master_stack_isce时给出了下面的错误。我想知道这个错误出现的原因是缺失文件，请问是那一步出现了问题，我应该怎么解决。）
ln: 无法创建符号链接 './20220208.slc.full.vrt': 不允许的操作
ln: 无法创建符号链接 './20220208.slc.full.xml': 不允许的操作
rm: 无法删除 '20220208.slc.full.vrt': 没有那个文件或目录
ERROR 4: 20220208.slc.full: No such file or directory
rm: 无法删除 '20220208.slc.full.xml': 没有那个文件或目录
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Traceback (most recent call last):
  File "/home/xiangben/anaconda3/envs/isce2_env/lib/python3.8/site-packages/isce/applications/gdal2isce_xml.py", line 133, in <module>
    raise Exception('Input file is not found ....')
Exception: Input file is not found ....
ln: 无法创建符号链接 'reference.slc': 不允许的操作
xml file for the SLC does not exist, you need to have these

this is my input_file
source_data slc_stack
slc_stack_path /media/xiangben/祥本硬盘/ubuntu/isce2/sbas/merged/SLC
slc_stack_reference 20220208
slc_stack_geom_path /media/xiangben/祥本硬盘/ubuntu/isce2/sbas/merged/geom_reference
slc_stack_baseline_path /media/xiangben/祥本硬盘/ubuntu/isce2/sbas/merged/interferograms
range_looks 20
azimuth_looks 5
aspect_ratio 4
lambda 0.056
slc_suffix .full
geom_suffix .full


I would like to know which step caused the problem and how I should resolve it, as the reason for this error is a missing file

This mistake has been bothering me for a long time. I really hope someone can help me, and I sincerely hope everyone can help me. I am extremely grateful
