### ISSUE TITLE
iscesys.Component.Component.PortError: 'No input port named sensor'

### ISSUE THREAD

**Issue by zyxgis** [isce-framework/isce2#717]
insarApp.xml  file's  content as follow

```xml
<?xml version="1.0" encoding="UTF-8"?>
<insarApp>
    <component name="insar">
        <property  name="Sensor name">ALOS2</property>
        <component name="reference">
            <property name="IMAGEFILE">/home/testUser/0000471428_001001_ALOS2441290770-220725/IMG-HH-ALOS2441290772-220725-UBDR1.1__A</property>
            <property name="LEADERFILE">/home/testUser/0000471428_001001_ALOS2441290770-220725/LED-ALOS2441290772-220725-UBDR1.1__A</property>
            <property name="OUTPUT">060810.raw</property>
        </component>
        <component name="secondary">
            <property name="IMAGEFILE">/home/testUser/0000471428_001001_ALOS2441290770-220725/IMG-HH-ALOS2441290772-220725-UBDR1.1__A</property>
            <property name="LEADERFILE">/home/testUser/0000471428_001001_ALOS2441290770-220725/LED-ALOS2441290772-220725-UBDR1.1__A</property>
            <property name="OUTPUT">061110.raw</property>
        </component>
    </component>
</insarApp>

```

--------------------------
the command: 

```shell
$ /python/compile/bin/python3 /home/testUser/isce/packages/isce2/applications/insarApp.py /home/testUser/insarApp.xml --steps

```

--------------------------

the output: 

```
2023-05-19 16:30:03,870 - isce.insar - INFO - ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION =
ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION =
Step processing
Running step startup

    Insar Application:
    Implements InSAR processing flow for a pair of scenes from
    sensor raw data to geocoded, flattened interferograms.

The currently supported sensors are:  ['ALOS', 'ALOS2', 'ALOS_SLC', 'COSMO_SKYMED', 'COSMO_SKYMED_SLC', 'ENVISAT', 'ENVISAT_SLC', 'ERS', 'ERS_ENVISAT', 'ERS_ENVISAT_SLC', 'ERS_SLC', 'ICEYE_SLC', 'KOMPSAT5', 'RADARSAT1', 'RADARSAT2', 'RISAT1', 'RISAT1_SLC', 'ROI_PAC', 'SAOCOM_SLC', 'SENTINEL1', 'SICD_RGZERO', 'TERRASARX', 'UAVSAR_HDF5_SLC', 'UAVSAR_POLSAR', 'UAVSAR_RPI', 'UAVSAR_STACK']
Dumping the application's pickle object _insar to file  PICKLE/startup
The remaining steps are (in order):  ['preprocess', 'verifyDEM', 'pulsetiming', 'estimateHeights', 'mocompath', 'orbit2sch', 'updatepreprocinfo', 'formslc', 'offsetprf', 'outliers1', 'prepareresamps', 'resamp', 'resamp_image', 'mocompbaseline', 'settopoint1', 'topo', 'shadecpx2rg', 'rgoffset', 'rg_outliers2', 'resamp_only', 'settopoint2', 'correct', 'coherence', 'filter', 'mask', 'unwrap', 'unwrap2stage', 'geocode']
Running step preprocess
2023-05-19 16:30:04,120 - isce.make_raw - INFO - Extracting image
2023-05-19 16:30:04,152 - isce.sensor.alos2 - DEBUG - Extracting line 0
2023-05-19 16:30:05,276 - isce.sensor.alos2 - DEBUG - Extracting line 1000
2023-05-19 16:30:06,436 - isce.sensor.alos2 - DEBUG - Extracting line 2000
2023-05-19 16:30:07,580 - isce.sensor.alos2 - DEBUG - Extracting line 3000
2023-05-19 16:30:08,702 - isce.sensor.alos2 - DEBUG - Extracting line 4000
2023-05-19 16:30:09,823 - isce.sensor.alos2 - DEBUG - Extracting line 5000
2023-05-19 16:30:10,957 - isce.sensor.alos2 - DEBUG - Extracting line 6000
2023-05-19 16:30:12,081 - isce.sensor.alos2 - DEBUG - Extracting line 7000
2023-05-19 16:30:13,215 - isce.sensor.alos2 - DEBUG - Extracting line 8000
2023-05-19 16:30:14,347 - isce.sensor.alos2 - DEBUG - Extracting line 9000
2023-05-19 16:30:15,471 - isce.sensor.alos2 - DEBUG - Extracting line 10000
2023-05-19 16:30:16,604 - isce.sensor.alos2 - DEBUG - Extracting line 11000
2023-05-19 16:30:17,726 - isce.sensor.alos2 - DEBUG - Extracting line 12000
2023-05-19 16:30:18,860 - isce.sensor.alos2 - DEBUG - Extracting line 13000
2023-05-19 16:30:19,980 - isce.sensor.alos2 - DEBUG - Extracting line 14000
2023-05-19 16:30:21,081 - isce.sensor.alos2 - DEBUG - Extracting line 15000
2023-05-19 16:30:22,198 - isce.sensor.alos2 - DEBUG - Extracting line 16000
2023-05-19 16:30:23,321 - isce.sensor.alos2 - DEBUG - Extracting line 17000
2023-05-19 16:30:24,445 - isce.sensor.alos2 - DEBUG - Extracting line 18000
2023-05-19 16:30:25,561 - isce.sensor.alos2 - DEBUG - Extracting line 19000
2023-05-19 16:30:26,680 - isce.sensor.alos2 - DEBUG - Extracting line 20000
2023-05-19 16:30:27,795 - isce.sensor.alos2 - DEBUG - Extracting line 21000
2023-05-19 16:30:28,910 - isce.sensor.alos2 - DEBUG - Extracting line 22000
2023-05-19 16:30:30,008 - isce.sensor.alos2 - DEBUG - Extracting line 23000
2023-05-19 16:30:31,120 - isce.sensor.alos2 - DEBUG - Extracting line 24000
2023-05-19 16:30:32,256 - isce.sensor.alos2 - DEBUG - Extracting line 25000
2023-05-19 16:30:33,371 - isce.sensor.alos2 - DEBUG - Extracting line 26000
2023-05-19 16:30:34,525 - isce.sensor.alos2 - DEBUG - Extracting line 27000
2023-05-19 16:30:35,652 - isce.sensor.alos2 - DEBUG - Extracting line 28000
2023-05-19 16:30:36,766 - isce.sensor.alos2 - DEBUG - Extracting line 29000
2023-05-19 16:30:37,878 - isce.sensor.alos2 - DEBUG - Extracting line 30000
2023-05-19 16:30:39,020 - isce.sensor.alos2 - DEBUG - Extracting line 31000
2023-05-19 16:30:40,144 - isce.sensor.alos2 - DEBUG - Extracting line 32000
2023-05-19 16:30:41,276 - isce.sensor.alos2 - DEBUG - Extracting line 33000
2023-05-19 16:30:42,407 - isce.sensor.alos2 - DEBUG - Extracting line 34000
2023-05-19 16:30:43,509 - isce.sensor.alos2 - DEBUG - Extracting line 35000
2023-05-19 16:30:44,763 - isce.sensor.alos2 - DEBUG - Extracting line 36000
2023-05-19 16:30:45,893 - isce.sensor.alos2 - DEBUG - Extracting line 37000
API open (R): 060810.raw
API close:  060810.raw
Traceback (most recent call last):
  File "/home/testUser/isce/packages/isce2/applications/insarApp.py", line 1215, in <module>
    status = insar.run()
  File "/home/testUser/isce/packages/isce/components/iscesys/Component/Application.py", line 142, in run
    exitStatus = self._processSteps()
  File "/home/testUser/isce/packages/isce/components/iscesys/Component/Application.py", line 405, in _processSteps
    result = func(*pargs, **kwargs)
  File "/home/testUser/isce/packages/isce/components/isceobj/InsarProc/Factories.py", line 66, in __call__
    return self.method(self.other, *args, **kwargs)
  File "/home/testUser/isce/packages/isce/components/isceobj/Util/decorators.py", line 290, in use_api_decorator
    ret = func(*args,**kwargs)
  File "/home/testUser/isce/packages/isce/components/isceobj/InsarProc/runPreprocessor.py", line 38, in runPreprocessor
    reference = make_raw(self.reference, self.referencedop)
  File "/home/testUser/isce/packages/isce/components/isceobj/InsarProc/runPreprocessor.py", line 153, in make_raw
    objMakeRaw(sensor=sensor, doppler=doppler)
  File "/home/testUser/isce/packages/isce/components/iscesys/Component/Component.py", line 179, in __call__
    return getattr(self, self.__class__.__name__.lower())(*args)
  File "/home/testUser/isce/packages/isce2/applications/make_raw.py", line 288, in make_raw
    self.doppler.wireInputPort(name='sensor', object=self.sensor)
  File "/home/testUser/isce/packages/isce/components/iscesys/Component/Component.py", line 157, in method_with_flow
    return method(self)(*args, **kwargs)
  File "/home/testUser/isce/packages/isce/components/iscesys/Component/Component.py", line 259, in _wirePort
    raise PortError("No %s port named %s" % (port_iterator.flow, name))
iscesys.Component.Component.PortError: 'No input port named sensor'
```

**Comment by EJFielding** [comment]
The ISCE2 `insarApp.py` requires some extra components that are not available in the GitHub version of ISCE, and it is also very old, so it is not going to work.

You can use `stripmapApp.py` instead for many satellites, or because you are processing ALOS-2 data you can use `alos2App.py` that is specially optimized for ALOS-2 data.
