### ISSUE TITLE
Geocoding Radarsat-2 with stripmapApp

### ISSUE THREAD

**Issue by pburgi-usgs** [isce-framework/isce2#724]
I am having trouble geocoding Radarsat-2 data during both the "geocode" and "geocodeoffsets" steps using isce2. The denseoffset and interferogram files all processed correctly. Here is the output I get when running the geocoding step: 

```
(isce2_python3.6) pburgi@igskcicgusclst2:/insar/pburgi/response/Turkey_022023/radarsat2/int2_denseoffset_w32sw10s16$ stripmapApp.py 20230114_20230207.xml --steps --dostep=geocode
2023-05-26 14:16:08,997 - isce.insar - INFO - ISCE VERSION = 2.5.1, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20210305, CURRENT_SVN_REVISION = 
ISCE VERSION = 2.5.1, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20210305, CURRENT_SVN_REVISION = 
2023-05-26 14:16:09,000 - root - INFO - reference sensor not provided explicitly, using common sensor
2023-05-26 14:16:09,037 - root - INFO - secondary sensor not provided explicitly, using common sensor
do_unwrap  False
Step processing
Running step geocode
2023-05-26 14:16:09,135 - isce.topsinsar.runGeocode - INFO - Geocoding Image
Number of products to geocode:  1
Traceback (most recent call last):
  File "/data/pburgi/software/miniconda3/envs/isce2_python3.6/lib/python3.6/site-packages/isce/applications/stripmapApp.py", line 1002, in <module>
    status = insar.run()
  File "/data/pburgi/software/miniconda3/envs/isce2_python3.6/lib/python3.6/site-packages/isce/components/iscesys/Component/Application.py", line 142, in run
    exitStatus = self._processSteps()
  File "/data/pburgi/software/miniconda3/envs/isce2_python3.6/lib/python3.6/site-packages/isce/components/iscesys/Component/Application.py", line 405, in _processSteps
    result = func(*pargs, **kwargs)
  File "/data/pburgi/software/miniconda3/envs/isce2_python3.6/lib/python3.6/site-packages/isce/components/isceobj/StripmapProc/Factories.py", line 46, in __call__
    return self.method(self.other, *args, **kwargs)
  File "/data/pburgi/software/miniconda3/envs/isce2_python3.6/lib/python3.6/site-packages/isce/components/isceobj/StripmapProc/runGeocode.py", line 55, in runGeocode
    burst = self._insar.loadProduct( self._insar.referenceSlcCropProduct)
  File "/data/pburgi/software/miniconda3/envs/isce2_python3.6/lib/python3.6/site-packages/isce/components/isceobj/StripmapProc/StripmapProc.py", line 602, in loadProduct
    obj = pm.loadProduct(xmlname)
  File "/data/pburgi/software/miniconda3/envs/isce2_python3.6/lib/python3.6/site-packages/isce/components/iscesys/Component/ProductManager.py", line 25, in loadProduct
    self.load(filename)
  File "/data/pburgi/software/miniconda3/envs/isce2_python3.6/lib/python3.6/site-packages/isce/components/iscesys/Component/Configurable.py", line 1407, in load
    tmpProp, tmpFact, tmpMisc = FP.parse(filename)
  File "/data/pburgi/software/miniconda3/envs/isce2_python3.6/lib/python3.6/site-packages/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse
    root = ET.parse(filename)
  File "/data/pburgi/software/miniconda3/envs/isce2_python3.6/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/data/pburgi/software/miniconda3/envs/isce2_python3.6/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Here is my xml file: 

```
<?xml version="1.0" encoding="UTF-8"?>
<insarApp>
  <component name="insar">
    <property name="sensor name">RADARSAT2</property>
    <component name="reference">
        <catalog>20230114.xml</catalog>
    </component>
    <component name="secondary">
        <catalog>20230207.xml</catalog>
    </component>
    <property name="demFilename">
        <value>/insar/pburgi/response/Turkey_022023/radarsat2/dem/demLat_N36_N39_Lon_E036_E039_upsample3x.dem.wgs84</value>
    </property>
    <!--
               <property name="do rubbersheetingAzimuth">True</property>
      <property name="do rubbersheetingRange">False</property>
    -->
    <property name="do denseoffsets">True</property>
    <property name="dense window width">32</property>
    <property name="dense window height">32</property>
    <property name="dense search width">10</property>
    <property name="dense search height">10</property>
    <property name="dense skip width">16</property>
    <property name="dense skip height">16</property>
    <property name="range looks">2</property>
    <property name="azimuth looks">2</property>
    <property name="do split spectrum">False</property>
    <!--<property name="unwrapper name">snaphu</property>--> 
    <property name="do unwrap">False</property>
    <property name="do dispersive">False</property>
    <property name="geocode list">["interferogram/filt_topophase.flat"]</property>
    <property name="offset geocode list">["denseOffsets/denseOffsets.bil"]</property>

  </component>
</insarApp>
```

Any guidance would be much appreciated, thank you!

**Comment by EJFielding** [comment]
Hi Paula,

Did you run all the steps of `stripmapApp.py` before the `geocode` step? It looks like you have the `do_unwrap` flag set to False, but you might need to run the `unwrap` step to make sure all the files that the `geocode` step needs are available.
++Eric

**Comment by pburgi-usgs** [comment]
Hi Eric, 

Yes, that was the problem. Thanks!
