### ISSUE TITLE
Two errors while running run_01_unpack_topo_reference

### ISSUE THREAD

**Issue by ranneylxr** [isce-framework/isce2#762]
I am stacking Sentinel-1 images for StaMPS processing.  And I meet two errors:
`sh run_01_unpack_topo_reference`
The output message is:
Completed Parsing the Configuration file
Functions to be executed:
['Function-1', 'Function-2']
Running: Sentinel1_TOPS
['--dirname', '/scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.zip /scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.zip', '--swaths', '2', '--orbitdir', '/work2/09401/xlv/stampede2/insarlab/S1orbits', '--outdir', '/scratch/09401/xlv/EifelSenDT139_SP/reference', '--auxdir', '/work2/09401/xlv/stampede2/insarlab/S1aux', '--bbox', '49.55 51.35 6.50 8.60', '--pol', 'vv']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Input XML files:  ['/vsizip//scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.zip/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.SAFE/annotation/s1a-iw2-slc-vv-20220623t054222-20220623t054247-043786-053a33-005.xml', '/vsizip//scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.zip/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.SAFE/annotation/s1a-iw2-slc-vv-20220623t054246-20220623t054312-043786-053a33-005.xml']
Input TIFF files:  ['/vsizip//scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.zip/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.SAFE/measurement/s1a-iw2-slc-vv-20220623t054222-20220623t054247-043786-053a33-005.tiff', '/vsizip//scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.zip/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.SAFE/measurement/s1a-iw2-slc-vv-20220623t054246-20220623t054312-043786-053a33-005.tiff']
Manifest files:  ['/vsizip//scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.zip/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.SAFE/manifest.safe', '/vsizip//scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.zip/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.SAFE/manifest.safe']
Input XML files:  ['/vsizip//scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.zip/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.SAFE/annotation/s1a-iw2-slc-vv-20220623t054222-20220623t054247-043786-053a33-005.xml']
Input TIFF files:  ['/vsizip//scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.zip/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.SAFE/measurement/s1a-iw2-slc-vv-20220623t054222-20220623t054247-043786-053a33-005.tiff']
MANS:  /scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.zip S1A_IW_SLC__1SDV_20220623T054221_20220623T054248_043786_053A33_F595.SAFE/manifest.safe
Setting IPF version to :  003.52
Extracting orbit from Orbit File:  /work2/09401/xlv/stampede2/insarlab/S1orbits/S1A_OPER_AUX_POEORB_OPOD_20220713T081826_V20220622T225942_20220624T005942.EOF
Number of Bursts before cropping:  9
Number of Bursts after cropping:  5
Input XML files:  ['/vsizip//scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.zip/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.SAFE/annotation/s1a-iw2-slc-vv-20220623t054246-20220623t054312-043786-053a33-005.xml']
Input TIFF files:  ['/vsizip//scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.zip/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.SAFE/measurement/s1a-iw2-slc-vv-20220623t054246-20220623t054312-043786-053a33-005.tiff']
MANS:  /scratch/09401/xlv/EifelSenDT139_SP/SLC/S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.zip S1A_IW_SLC__1SDV_20220623T054245_20220623T054312_043786_053A33_8335.SAFE/manifest.safe
Setting IPF version to :  003.52
Extracting orbit from Orbit File:  /work2/09401/xlv/stampede2/insarlab/S1orbits/S1A_OPER_AUX_POEORB_OPOD_20220713T081826_V20220622T225942_20220624T005942.EOF
Number of Bursts before cropping:  9
Number of Bursts after cropping:  8
Stitching 2 slices together
**module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations**
Running: topo
['--reference', '/scratch/09401/xlv/EifelSenDT139_SP/reference', '--dem', '/scratch/09401/xlv/EifelSenDT139_SP/DEM/demLat_N46_N54_Lon_E004_E012.dem.wgs84', '--geom_referenceDir', '/scratch/09401/xlv/EifelSenDT139_SP/geom_reference', '--numProcess', '8']
running in parallel with 8 processes
Traceback (most recent call last):
  File "/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/topo.py", line 112, in main
    bbox = [np.min(boxes[:,0]), np.max(boxes[:,1]), np.min(boxes[:,2]), np.max(boxes[:,3])]
**IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed**

But I can't find where the `np.int` appears in the isce scripts. Please check the `grep` results:
```
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/prep4timeseries.py:20:3 : np.int16,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/prep4timeseries.py:22:5 : np.int32,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/MaskAndFilter.py:21:3 : np.int16,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/MaskAndFilter.py:23:5 : np.int32,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/computeIon.py:55:    #     n = np.int32(len(inps.masked_areas)/4)
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/rubberSheeting.py:23:3 : np.int16,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/rubberSheeting.py:25:5 : np.int32,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/Stack.py:1279:                    configObj.rvalid = np.int32(np.around(ionParamUsrObj.ION_numberRangeLooks/8.0))
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/Stack.py:1390:                    configObj.nrlks = np.int32(np.around(ionParamUsrObj.ION_numberRangeLooks / ionParamUsrObj.ION_numberRangeLooks0))
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/Stack.py:1391:                    configObj.nalks = np.int32(np.around(ionParamUsrObj.ION_numberAzimuthLooks / ionParamUsrObj.ION_numberAzimuthLooks0))
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/Stack.py:1397:                #configObj.nrlks = np.int32(np.around(ionParamUsrObj.ION_numberRangeLooks / ionParamUsrObj.ION_numberRangeLooks0))
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/Stack.py:1398:                #configObj.nalks = np.int32(np.around(ionParamUsrObj.ION_numberAzimuthLooks / ionParamUsrObj.ION_numberAzimuthLooks0))
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/Stack.py:1410:                    configObj.nrlks = np.int32(np.around(ionParamUsrObj.ION_numberRangeLooks / ionParamUsrObj.ION_numberRangeLooks0))
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/Stack.py:1411:                    configObj.nalks = np.int32(np.around(ionParamUsrObj.ION_numberAzimuthLooks / ionParamUsrObj.ION_numberAzimuthLooks0))
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/Stack.py:1420:                    #configObj.nrlks = np.int32(np.around(ionParamUsrObj.ION_numberRangeLooks / ionParamUsrObj.ION_numberRangeLooks0))
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/topsStack/Stack.py:1421:                    #configObj.nalks = np.int32(np.around(ionParamUsrObj.ION_numberAzimuthLooks / ionParamUsrObj.ION_numberAzimuthLooks0))
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/stripmapStack/MaskAndFilter.py:28:    3 : np.int16,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/stripmapStack/MaskAndFilter.py:30:    5 : np.int32,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/stripmapStack/resampleOffsets.py:19:3 : np.int16,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/stripmapStack/resampleOffsets.py:21:5 : np.int32,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/stripmapStack/prepStripmap4timeseries.py:21:3 : np.int16,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/stripmapStack/prepStripmap4timeseries.py:23:5 : np.int32,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/stripmapStack/rubberSheeting.py:20:3 : np.int16,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/stripmapStack/rubberSheeting.py:22:5 : np.int32,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/stripmapStack/reader.py:19:3 : np.int16,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/stripmapStack/reader.py:21:5 : np.int32,
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/alosStack/ion_filt.py:90:    wbd = np.fromfile('wbd'+ml2+'.wbd', dtype=np.int8).reshape(length, width)
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/alosStack/ion_filt.py:189:    wbd = np.fromfile('wbd'+ml2+'.wbd', dtype=np.int8).reshape(length, width)
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/alosStack/ion_filt.py:196:    #     wbd = np.fromfile(waterBodyFile, dtype=np.in8).reshape(length, width)
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/alosStack/ion_filt.py:255:    win2 = np.zeros(cor2.size, dtype=np.int32)
/work2/09401/xlv/stampede2/software/rsmas_insar/tools/miniconda3/share/isce2/TOPS/Sentinel1.py:1143:        theta = np.interp(tau, tau_sub, theta_sub)
```
Could the `np.int` error induce the `IndexError`?
If anybody has any ideas, please give me some suggestions.
Thank you.

**Comment by ranneylxr** [comment]
Now it is runing fine. There is a 'np.int' in python/site-package/isce/components/isceobj/Sensor/TOPS/Sentinel1.py
