### ISSUE TITLE
run_03_geo2rdr_coarseResamp error

### ISSUE THREAD

**Issue by xialuwen** [isce-framework/isce2#763]
```
Running: resampleSlc
['--reference', '/media/xia/D/envisat/SLC/20040729', '--secondary', '/media/xia/D/envisat/SLC/20041007', '--coreg', '/media/xia/D/envisat/coregSLC/Coarse/20041007', '--offsets', '/media/xia/D/envisat/offsets/20041007']
cp /media/xia/D/envisat/SLC/20041007/data* /media/xia/D/envisat/coregSLC/Coarse/20041007/secondaryShelve
Traceback (most recent call last):
  File "/home/xia/anaconda3/envs/isce2_env/lib/python3.8/site-packages/isce/contrib/stack/stripmapStack/stripmapWrapper.py", line 155, in <module>
    main(args.start,args.end)
  File "/home/xia/anaconda3/envs/isce2_env/lib/python3.8/site-packages/isce/contrib/stack/stripmapStack/stripmapWrapper.py", line 146, in main
    cfgParser.runCmd()
  File "/home/xia/anaconda3/envs/isce2_env/lib/python3.8/site-packages/isce/contrib/stack/stripmapStack/stripmapWrapper.py", line 51, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/xia/anaconda3/envs/isce2_env/lib/python3.8/site-packages/isce/contrib/stack/stripmapStack/resampleSlc.py", line 215, in main
    resampSecondary(secondary, inps.offsets, outfile,
  File "/home/xia/anaconda3/envs/isce2_env/lib/python3.8/site-packages/isce/components/isceobj/Util/decorators.py", line 290, in use_api_decorator
    ret = func(*args,**kwargs)
  File "/home/xia/anaconda3/envs/isce2_env/lib/python3.8/site-packages/isce/contrib/stack/stripmapStack/resampleSlc.py", line 106, in resampSecondary
    inimg.load(burst.getImage().filename + '.xml')
  File "/home/xia/anaconda3/envs/isce2_env/lib/python3.8/site-packages/isce/components/iscesys/Component/Configurable.py", line 1407, in load
    tmpProp, tmpFact, tmpMisc = FP.parse(filename)
  File "/home/xia/anaconda3/envs/isce2_env/lib/python3.8/site-packages/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse
    root = ET.parse(filename)
  File "/home/xia/anaconda3/envs/isce2_env/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/home/xia/anaconda3/envs/isce2_env/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'SLC/20041007/20041007.slc.xml'
```

**Comment by saeedmhanna1** [comment]
Hello, 

I am having the same issue. Were you able to solve it?

**Comment by alexnaoki** [comment]
The program is not finding this file because it has been used as a relative path.
Try rerunning it, corrected from your parent directory, for the program to be able to find this file correctly.

`cd /media/xia/D/envisat`

Then, run the program.

**Comment by rtburns-jpl** [comment]
Looks like alexnaoki's solution is correct, as it seems to have worked for saeedmhanna1 based on the thumbs-up. I'll close this as resolved, but feel free to reopen if this isn't the case.

**Comment by keepfighting666** [comment]
> Looks like alexnaoki's solution is correct, as it seems to have worked for saeedmhanna1 based on the thumbs-up. I'll close this as resolved, but feel free to reopen if this isn't the case.

Running: resampleSlc
['--reference', '/media/seven/J/477530/SLC/20081211', '--secondary', '/media/seven/J/477530/SLC/20061206', '--coreg', '/media/seven/J/477530/rslc/coregSLC/Coarse/20061206', '--offsets', '/media/seven/J/477530/rslc/offsets/20061206']
cp /media/seven/J/477530/SLC/20061206/data* /media/seven/J/477530/rslc/coregSLC/Coarse/20061206/secondaryShelve
Polynomial doppler provided
List of coefficients provided
Traceback (most recent call last):
  File "/home/seven/tools/isce2/src/isce2/contrib/stack/stripmapStack/resampleSlc.py", line 118, in resampSecondary
    coeffs = [factor * 2*np.pi*val/prf for val in doppler._coeffs]
                                                  ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_coeffs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seven/tools/isce2/src/isce2/contrib/stack/stripmapStack/stripmapWrapper.py", line 155, in <module>
    main(args.start,args.end)
  File "/home/seven/tools/isce2/src/isce2/contrib/stack/stripmapStack/stripmapWrapper.py", line 146, in main
    cfgParser.runCmd()
  File "/home/seven/tools/isce2/src/isce2/contrib/stack/stripmapStack/stripmapWrapper.py", line 51, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/seven/tools/isce2/src/isce2/contrib/stack/stripmapStack/resampleSlc.py", line 215, in main
    resampSecondary(secondary, inps.offsets, outfile,
  File "/home/anaconda3/envs/insar/lib/python3.11/site-packages/isce/components/isceobj/Util/decorators.py", line 290, in use_api_decorator
    ret = func(*args,**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/seven/tools/isce2/src/isce2/contrib/stack/stripmapStack/resampleSlc.py", line 121, in resampSecondary
    coeffs = [factor * 2*np.pi*val/prf for val in doppler]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
Completed Parsing the Configuration file

hello, i have a new issue, can u help me? Thanks a lot.
