### ISSUE TITLE
Error while trying to use "stripmapStack" process with ALOS-1 data

### ISSUE THREAD

**Issue by saeedmhanna1** [isce-framework/isce2#768]
I was following these steps [stripmapStack](https://github.com/isce-framework/isce2/tree/main/contrib/stack/stripmapStack#32-download-the-data-that-that-you-want-to-process-to-the-downlowd-directory) with some **ALOS-1** data that I downloaded from [ASF Vertex](https://search.asf.alaska.edu/#/?dataset=ALOS), however when I tried to run the executable **_"run_unPackALOS"_** from the step **5** in the first link above this error showed up.

PS: I am trying to run 4 images (Level 1.1 Complex) using the OpenSARLab.

`python
/home/jovyan/ALOS_Hama/run_unPackALOS: 1: source: not found
['/home/jovyan/ALOS_Hama/download/ARCHIVED_FILES/20070711/ALPSRP077860690/LED-ALPSRP077860690-H1.1__A']
['/home/jovyan/ALOS_Hama/download/ARCHIVED_FILES/20070711/ALPSRP077860690/IMG-HH-ALPSRP077860690-H1.1__A']
/home/jovyan/ALOS_Hama/download/SLC/20070711/20070711.raw
2023-09-17 14:52:17,029 - isce.sensor.ALOS - INFO - Extracting Level 1.1 data
Traceback (most recent call last):
  File "/home/jovyan/.local/envs/insar_analysis/share/isce2/stripmapStack//unpackFrame_ALOS_raw.py", line 123, in <module>
    unpack(inps.h5dir, inps.slcdir, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.local/envs/insar_analysis/share/isce2/stripmapStack//unpackFrame_ALOS_raw.py", line 85, in unpack
    obj.extractImage()
  File "/home/jovyan/.local/envs/insar_analysis/lib/python3.11/site-packages/isce/components/isceobj/Sensor/ALOS.py", line 516, in extractImage
    self.imageFile.extractImage(outputNow, i) #image number start with 0
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.local/envs/insar_analysis/lib/python3.11/site-packages/isce/components/isceobj/Sensor/ALOS.py", line 732, in extractImage
    self.extractSLC(output)
  File "/home/jovyan/.local/envs/insar_analysis/lib/python3.11/site-packages/isce/components/isceobj/Sensor/ALOS.py", line 821, in extractSLC
    fp.seek(self.HEADER_LINES, os.SEEK_SET) # Skip the header
            ^^^^^^^^^^^^^^^^^
AttributeError: 'ImageFile' object has no attribute 'HEADER_LINES'
`

**Comment by EJFielding** [comment]
Hi Saeed,

The unpack_ALOS1 script is designed for raw or level 1.0 ALOS data.
