### ISSUE TITLE
Issues with ALOS2 Stripmap Fine (SM3) processing with alosStack

### ISSUE THREAD

**Issue by fgdiazm** [isce-framework/isce2#773]
Hello everyone

I'm trying to process ALOS2 Stripmap Fine (SM3) images, following the instructions in alosStack_tutorial.txt, however I get this error

Traceback (most recent call last):
  File "/opt/isce2/src/isce2/contrib/stack/alosStack/create_cmds.py", line 1363, in <module>
    checkStackDataDir(stack.dataDir)
  File "/opt/isce2/src/isce2/contrib/stack/alosStack/create_cmds.py", line 230, in checkStackDataDir
    mode = os.path.basename(sorted(glob.glob(os.path.join(dateDirs[0], 'IMG-HH-ALOS2*')))[0]).split('-')[4][0:3]
IndexError: list index out of range

I created the folders by dates and in them I introduced the images as they appear here

data/150310/

VOL-ALOS2042963520-150310-FBDR1.1__D
TRL-ALOS2042963520-150310-FBDR1.1__D
summary.txt
LED-ALOS2042963520-150310-FBDR1.1__D
IMG-HV-ALOS2042963520-150310-FBDR1.1__D
IMG-HH-ALOS2042963520-150310-FBDR1.1__D
BRS-HV-ALOS2042963520-150310-FBDR1.1__D.jpg
BRS-HH-ALOS2042963520-150310-FBDR1.1__D.jpg

![prob proc](https://github.com/isce-framework/isce2/assets/92444444/ef65294a-c7f6-4111-a01f-0b8d581c405d)

Is there any error in the data?

I appreciate your help, thank you

**Comment by EJFielding** [comment]
Check that all of the subdirectories under your "data" directory have `IMG-HH-ALOS2` data in them. This error usually happens when there is a subdirectory without data in it.

**Comment by fgdiazm** [comment]
Hi Eric

I already detected the error, it was an empty folder that I had not been able to delete, so I moved all the folders with the images and it worked

thank you

**Comment by EJFielding** [comment]
Great to hear that you solved the problem. Please close the issue.
