### ISSUE TITLE
run_05_invertMisreg error 

### ISSUE THREAD

**Issue by saeedmhanna1** [isce-framework/isce2#776]
Hello all,

I just want to bring this error back, which was previously referred to in this discussion #488. 

I am getting this error message after running the 5th run file (invertMisreg): 

I am using stripmapStack to create a stack of ENVISAT images. 

Any feedback is greatly appreciated. 
`
/home/jovyan/Envisat_Hama/refineSecondaryTiming/pairs/20031111_20050208
['_MutableMapping__marker', '__abstractmethods__', '__class__', '__class_getitem__', '__contains__', '__del__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__setitem__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_protocol', 'cache', 'clear', 'close', 'dict', 'get', 'items', 'keyencoding', 'keys', 'pop', 'popitem', 'setdefault', 'sync', 'update', 'values', 'writeback']
Traceback (most recent call last):
  File "/home/jovyan/.local/envs/insar_analysis/lib/python3.11/shelve.py", line 111, in __getitem__
    value = self.cache[key]
            ~~~~~~~~~~^^^^^
KeyError: 'azpoly'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jovyan/.local/envs/insar_analysis/share/isce2/stripmapStack//invertMisreg.py", line 207, in <module>
    main()
  File "/home/jovyan/.local/envs/insar_analysis/share/isce2/stripmapStack//invertMisreg.py", line 148, in main
    A, B, Laz, Lrg = design_matrix(pairDirs)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.local/envs/insar_analysis/share/isce2/stripmapStack//invertMisreg.py", line 126, in design_matrix
    azOff, rgOff = extract_offset(pairDirs[ni])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.local/envs/insar_analysis/share/isce2/stripmapStack//invertMisreg.py", line 69, in extract_offset
    azpoly = db['azpoly']
             ~~^^^^^^^^^^
  File "/home/jovyan/.local/envs/insar_analysis/lib/python3.11/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.local/envs/insar_analysis/lib/python3.11/dbm/dumb.py", line 148, in __getitem__
    pos, siz = self._index[key]     # may raise KeyError
               ~~~~~~~~~~~^^^^^
KeyError: b'azpoly'
`

**Comment by EJFielding** [comment]
Did you try this suggestion?
https://github.com/isce-framework/isce2/discussions/488#discussioncomment-3482353

**Comment by saeedmhanna1** [comment]
The reply you referred to is related to the unpackFrame_ENV. py step. 

My error arises after running run_05_invertMisreg and is related to azpoly.

**Comment by EJFielding** [comment]
Yes, but the `azpoly` needs to be set in the first unpackFrame step for all the Envisat scenes. If it is not in the metadata database, it might only cause the error much later in the processing.

**Comment by saeedmhanna1** [comment]
Thanks for the clarification. I had already included that correction in the unpackFrame step before running. Also might be worth adding but when I ran the same step with 4 images it previously worked. now i am trying a bigger stack (27 images from 2002 to 2010) and this error showed up.

**Comment by EJFielding** [comment]
It seems that the `azpoly` metadata is missing for at least one of your scenes, from the error message. Either it was missed in the initial unpacking or it was lost in the processing. Did all of your runs before "run_05" complete successfully?

**Comment by saeedmhanna1** [comment]
All runs files before "run_05" were successful. However, as you mentioned,
I expect one of the images is corrupted, since i ran ISCE with fewer images
and it worked perfectly. Is there a way to check this azpoly metadata
before? especially because "run_05" is taking a lot of time (8 hours in my
case for 27 images").

Thanks a lot Eric,
Saeed

**Comment by EJFielding** [comment]
The error message was for the pair `20031111_20050208` so one of those two images is probably the bad one. Unfortunately, the ISCE2 topsStack workflow stores all the metadata in "shelve" files that are binary files and are not easily checked. You would have to write some Python code to load the database from those files to check them.
