### ISSUE TITLE
TopsAPP error

### ISSUE THREAD

**Issue by ukmkkpk** [isce-framework/isce2#779]
Hi ISCE team：
I am trying to perform DInSAR of two Sentinel-1 IW SLC data. I installed ISCE through that guide(https://github.com/lijun99/isce2-install#linux-with-anaconda3--cmake) 

I am unable to follow the error saying Could not extract swath 1 and No annotation XML found inside the SAFE/ zip file. I am able to find the XML files as shown below. Although I have added the polarization property as followed by previous discussion https://github.com/isce-framework/isce2/discussions/495 but I could not resolve this issue and my isce2 version is 2.6.3.

 I am able to find the XML files as shown below
```
(isce2) maqingbo@maqingbo-VirtualBox:~/test/S1A_IW_SLC__1SSV_20160916T230503_20160916T230530_013084_014C21_A2E3.SAFE/annotation$ ls -ltr
总计 2436
-rw-r----- 1 maqingbo maqingbo 854127  9月 17  2016 s1a-iw2-slc-vv-20160916t230504-20160916t230530-013084-014c21-002.xml
-rw-r----- 1 maqingbo maqingbo 862168  9月 17  2016 s1a-iw1-slc-vv-20160916t230503-20160916t230529-013084-014c21-001.xml
-rw-r----- 1 maqingbo maqingbo 768179  9月 17  2016 s1a-iw3-slc-vv-20160916t230503-20160916t230528-013084-014c21-003.xml
drwxr-x--- 2 maqingbo maqingbo   4096 10月 18 14:13 calibration

``` 
Report an error:

```
(isce2) maqingbo@maqingbo-VirtualBox:~/test$ python $ISCE_HOME/applications/topsApp.py /home/maqingbo/test/insarApp.xml
2023-10-18 16:33:17,608 - isce.insar - INFO - ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION = 
ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION = 
None
The currently supported sensors are:  ['SENTINEL1']
Could not extract swath 1 from ['S1A_IW_SLC__1SSV_20160916T230503_20160916T230530_013084_014C21_A2E3.safe']
Generated error:  No annotation xml file found in S1A_IW_SLC__1SSV_20160916T230503_20160916T230530_013084_014C21_A2E3.safe
Could not extract swath 1 from ['S1A_IW_SLC__1SSV_20160921T231250_20160921T231317_013157_014E87_9BCB.safe']
Generated error:  No annotation xml file found in S1A_IW_SLC__1SSV_20160921T231250_20160921T231317_013157_014E87_9BCB.safe
Could not extract swath 2 from ['S1A_IW_SLC__1SSV_20160916T230503_20160916T230530_013084_014C21_A2E3.safe']
Generated error:  No annotation xml file found in S1A_IW_SLC__1SSV_20160916T230503_20160916T230530_013084_014C21_A2E3.safe
Could not extract swath 2 from ['S1A_IW_SLC__1SSV_20160921T231250_20160921T231317_013157_014E87_9BCB.safe']
Generated error:  No annotation xml file found in S1A_IW_SLC__1SSV_20160921T231250_20160921T231317_013157_014E87_9BCB.safe
Could not extract swath 3 from ['S1A_IW_SLC__1SSV_20160916T230503_20160916T230530_013084_014C21_A2E3.safe']
Generated error:  No annotation xml file found in S1A_IW_SLC__1SSV_20160916T230503_20160916T230530_013084_014C21_A2E3.safe
Could not extract swath 3 from ['S1A_IW_SLC__1SSV_20160921T231250_20160921T231317_013157_014E87_9BCB.safe']
Generated error:  No annotation xml file found in S1A_IW_SLC__1SSV_20160921T231250_20160921T231317_013157_014E87_9BCB.safe
2023-10-18 16:33:17,632 - isce.topsinsar.runPreprocessor - INFO - 
####################################################################################################
    runPreprocessor
----------------------------------------------------------------------------------------------------
common.Input list of swaths to process:  = [1, 2, 3]
####################################################################################################
Skipping processing for swath number IW-1
Skipping processing for swath number IW-2
Skipping processing for swath number IW-3
No swaths contain any burst overlaps ... cannot continue for interferometry applications
2023-10-18 16:33:17,633 - isce.topsinsar.runPreprocessor - INFO - 
####################################################################################################
    runComputeBaseline
----------------------------------------------------------------------------------------------------
####################################################################################################
Traceback (most recent call last):
  File "/home/maqingbo/tools/src/isce2/applications/topsApp.py", line 1077, in <module>
    insar.run()
  File "/home/maqingbo/anaconda3/envs/isce2/lib/python3.8/site-packages/isce/components/iscesys/Component/Application.py", line 144, in run
    exitStatus = self.main()
  File "/home/maqingbo/tools/src/isce2/applications/topsApp.py", line 996, in main
    self.verifyDEM()
  File "/home/maqingbo/anaconda3/envs/isce2/lib/python3.8/site-packages/isce/components/isceobj/TopsProc/Factories.py", line 40, in __call__
    return self.method(self.other, *args, **kwargs)
  File "/home/maqingbo/anaconda3/envs/isce2/lib/python3.8/site-packages/isce/components/isceobj/TopsProc/runVerifyDEM.py", line 76, in runVerifyDEM
    raise Exception('Something went wrong in determining bboxes')
Exception: Something went wrong in determining bboxes

``` 

my xml file：

```
1、 insarApp.xml
<topsApp>
  <component name="topsinsar">
    <property name="Sensor name">SENTINEL1</property>
    <component name="reference">
        <catalog>reference.xml</catalog>
    </component>
    <component name="secondary">
        <catalog>secondary.xml</catalog>
    </component>
  </component>
</topsApp>
2、reference.xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="reference">
  <property name="safe">
    <value>S1A_IW_SLC__1SSV_20160916T230503_20160916T230530_013084_014C21_A2E3.safe</value>
  </property>
  <property name="orbit directory">
      <value>orbit</value>
  </property>
  <property name="polarization">'vv'</property>
  <property name="output directory">
    <value>output/20160916</value>
  </property>
</component>
3、secondary.xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="secondary">
  <property name="safe">
    <value>S1A_IW_SLC__1SSV_20160921T231250_20160921T231317_013157_014E87_9BCB.safe</value>
  </property>
  <property name="orbit directory">
      <value>orbit</value>
  </property>
  <property name="polarization">'vv'</property>
  <property name="output directory">
    <value>output/20160921</value>
  </property>
</component>
```

**Comment by ukmkkpk** [comment]
If anyone can help me I would be very grateful

**Comment by ukmkkpk** [comment]
There may be a problem with the sentinel data or orbit file, just download it again.
