### ISSUE TITLE
TopsApp error

### ISSUE THREAD

**Issue by ukmkkpk** [isce-framework/isce2#781]
Dear ISCE develpers:

I am trying to perform DInSAR of two Sentinel-1 IW SLC data. I installed ISCE through that guide(https://github.com/lijun99/isce2-install#linux-with-anaconda3--cmake)

I posted an issue earlier today due to another TopsApp error (see the link for details，https://github.com/isce-framework/isce2/issues/779). Then I changed the image data. It seemed that the previous error was resolved (I'm not sure), but a new error appeared. Details are below.

This error message shows that 
```
Could not extract swath 1 from ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE']
Generated error:  not well-formed (invalid token): line 19, column 48

``` 
Complete error message
```
(isce2) maqingbo@maqingbo-VirtualBox:~/test1$ python $ISCE_HOME/applications/topsApp.py /home/maqingbo/test1/topsApp.xml
2023-10-19 00:34:57,130 - isce.insar - INFO - ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION = 
ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION = 
None
The currently supported sensors are:  ['SENTINEL1']
Input XML files:  ['S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/annotation/s1a-iw1-slc-vh-20220112t230513-20220112t230538-041434-04ed3c-001.xml']
Input TIFF files:  ['S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/measurement/s1a-iw1-slc-vh-20220112t230513-20220112t230538-041434-04ed3c-001.tiff']
Manifest files:  ['S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/manifest.safe']
Setting IPF version to :  003.40
Extracting orbit from Orbit File:  orbit/S1A_OPER_AUX_POEORB_OPOD_20220201T121555_V20220111T225942_20220113T005942.EOF
Updating burst number from 1 to 1
Updating burst number from 2 to 2
Updating burst number from 3 to 3
Updating burst number from 4 to 4
Updating burst number from 5 to 5
Updating burst number from 6 to 6
Updating burst number from 7 to 7
Updating burst number from 8 to 8
Updating burst number from 9 to 9
Input XML files:  ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/annotation/s1a-iw1-slc-vh-20220117t231321-20220117t231346-041507-04ef9f-001.xml']
Input TIFF files:  ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/measurement/s1a-iw1-slc-vh-20220117t231321-20220117t231346-041507-04ef9f-001.tiff']
Manifest files:  ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/manifest.safe']
Setting IPF version to :  003.40
Could not extract swath 1 from ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE']
Generated error:  not well-formed (invalid token): line 19, column 48
Input XML files:  ['S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/annotation/s1a-iw2-slc-vh-20220112t230511-20220112t230536-041434-04ed3c-002.xml']
Input TIFF files:  ['S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/measurement/s1a-iw2-slc-vh-20220112t230511-20220112t230536-041434-04ed3c-002.tiff']
Manifest files:  ['S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/manifest.safe']
Setting IPF version to :  003.40
Extracting orbit from Orbit File:  orbit/S1A_OPER_AUX_POEORB_OPOD_20220201T121555_V20220111T225942_20220113T005942.EOF
Updating burst number from 1 to 1
Updating burst number from 2 to 2
Updating burst number from 3 to 3
Updating burst number from 4 to 4
Updating burst number from 5 to 5
Updating burst number from 6 to 6
Updating burst number from 7 to 7
Updating burst number from 8 to 8
Updating burst number from 9 to 9
Input XML files:  ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/annotation/s1a-iw2-slc-vh-20220117t231322-20220117t231347-041507-04ef9f-002.xml']
Input TIFF files:  ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/measurement/s1a-iw2-slc-vh-20220117t231322-20220117t231347-041507-04ef9f-002.tiff']
Manifest files:  ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/manifest.safe']
Setting IPF version to :  003.40
Could not extract swath 2 from ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE']
Generated error:  not well-formed (invalid token): line 19, column 48
Input XML files:  ['S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/annotation/s1a-iw3-slc-vh-20220112t230512-20220112t230537-041434-04ed3c-003.xml']
Input TIFF files:  ['S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/measurement/s1a-iw3-slc-vh-20220112t230512-20220112t230537-041434-04ed3c-003.tiff']
Manifest files:  ['S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/manifest.safe']
Setting IPF version to :  003.40
Extracting orbit from Orbit File:  orbit/S1A_OPER_AUX_POEORB_OPOD_20220201T121555_V20220111T225942_20220113T005942.EOF
Updating burst number from 1 to 1
Updating burst number from 2 to 2
Updating burst number from 3 to 3
Updating burst number from 4 to 4
Updating burst number from 5 to 5
Updating burst number from 6 to 6
Updating burst number from 7 to 7
Updating burst number from 8 to 8
Updating burst number from 9 to 9
Input XML files:  ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/annotation/s1a-iw3-slc-vh-20220117t231320-20220117t231346-041507-04ef9f-003.xml']
Input TIFF files:  ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/measurement/s1a-iw3-slc-vh-20220117t231320-20220117t231346-041507-04ef9f-003.tiff']
Manifest files:  ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/manifest.safe']
Setting IPF version to :  003.40
Could not extract swath 3 from ['S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE']
Generated error:  not well-formed (invalid token): line 19, column 48
2023-10-19 00:34:58,176 - isce.topsinsar.runPreprocessor - INFO - 
####################################################################################################
    runPreprocessor
----------------------------------------------------------------------------------------------------
common.Input list of swaths to process:  = [1, 2, 3]
reference.burstLength_1 = 1494
reference.burstLength_2 = 1506
reference.burstLength_3 = 1512
reference.burstWidth_1 = 21165
reference.burstWidth_2 = 25119
reference.burstWidth_3 = 24306
reference.numberOfBursts_1 = 9
reference.numberOfBursts_2 = 9
reference.numberOfBursts_3 = 9
reference.sensor.ascendingnodetime = 2022-01-12 22:23:59.565969
reference.sensor.family = topsswathslc
reference.sensor.folder = None
reference.sensor.imagingmode = TOPS
reference.sensor.mission = S1A
reference.sensor.name = topsswathslc_name
reference.sensor.numberofbursts = 9
reference.sensor.processingfacility = Airbus Defence and Space-Toulouse, France
reference.sensor.processingsoftwareversion = 003.40
reference.sensor.processingsystem = Sentinel-1 IPF
reference.sensor.spacecraftname = Sentinel-1
####################################################################################################
Skipping processing for swath number IW-1
Skipping processing for swath number IW-2
Skipping processing for swath number IW-3
No swaths contain any burst overlaps ... cannot continue for interferometry applications
2023-10-19 00:34:58,177 - isce.topsinsar.runPreprocessor - INFO - 
####################################################################################################
    runComputeBaseline
----------------------------------------------------------------------------------------------------
####################################################################################################
Traceback (most recent call last):
  File "/home/maqingbo/tools/src/isce2/applications/topsApp.py", line 1077, in <module>
    insar.run()
  File "/home/maqingbo/anaconda3/envs/isce2/lib/python3.8/site-packages/isce/components/iscesys/Component/Application.py", line 144, in run
    exitStatus = self.main()
  File "/home/maqingbo/tools/src/isce2/applications/topsApp.py", line 996, in main
    self.verifyDEM()
  File "/home/maqingbo/anaconda3/envs/isce2/lib/python3.8/site-packages/isce/components/isceobj/TopsProc/Factories.py", line 40, in __call__
    return self.method(self.other, *args, **kwargs)
  File "/home/maqingbo/anaconda3/envs/isce2/lib/python3.8/site-packages/isce/components/isceobj/TopsProc/runVerifyDEM.py", line 76, in runVerifyDEM
    raise Exception('Something went wrong in determining bboxes')
Exception: Something went wrong in determining bboxes
```
 
my xml file
```
topsApp.xml
<?xml version="1.0" encoding="UTF-8"?>
<topsApp>
  <component name="topsinsar">
    <property name="Sensor name">SENTINEL1</property>
    <property name="filter strength">0.4</property>
    <component name="reference">
        <catalog>reference.xml</catalog>
    </component>
    <component name="secondary">
        <catalog>secondary.xml</catalog>
    </component>
  </component>
</topsApp>

reference.xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="reference">
  <property name="safe">
    <value>S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE</value>
  </property>
  <property name="orbit directory">
      <value>orbit</value>
  </property>
  <property name="polarization">'vh'</property>
  <property name="output directory">
    <value>output/20220112</value>
  </property>
</component>

secondary.xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="secondary">
  <property name="safe">
    <value>S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE</value>
  </property>
  <property name="orbit directory">
      <value>orbit</value>
  </property>
  <property name="polarization">'vh'</property>
  <property name="output directory">
    <value>output/20220117</value>
  </property>
</component>
```

**Comment by ukmkkpk** [comment]
Maybe there is a problem with the orbit file, just download it again in the linux system
