### ISSUE TITLE
TopsApp error ：Could not determine a suitable burst offset

### ISSUE THREAD

**Issue by ukmkkpk** [isce-framework/isce2#782]
Dear ISCE team：

I am trying to perform DInSAR of two Sentinel-1 IW SLC data. I installed ISCE through that guide(https://github.com/lijun99/isce2-install#linux-with-anaconda3--cmake)

But during the process of running TopsApp, a new problem appeared here, and it reported an error: Could not determine a suitable burst offset (Details are below) . I don’t know why this is happening, I hope someone can help me, thank you again!!

ERROR MESSAGE:
```
(isce2) maqingbo@maqingbo-VirtualBox:~/test2$ python $ISCE_HOME/applications/topsApp.py /home/maqingbo/test2/topsApp.xml
2023-10-19 12:20:11,574 - isce.insar - INFO - ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION = 
ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION = 
None
The currently supported sensors are:  ['SENTINEL1']
Input XML files:  ['/vsizip/S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.zip/S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/annotation/s1a-iw2-slc-vh-20220112t230511-20220112t230536-041434-04ed3c-002.xml']
Input TIFF files:  ['/vsizip/S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.zip/S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/measurement/s1a-iw2-slc-vh-20220112t230511-20220112t230536-041434-04ed3c-002.tiff']
Manifest files:  ['/vsizip/S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.zip/S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/manifest.safe']
MANS:  S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.zip S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.SAFE/manifest.safe
Setting IPF version to :  003.40
Extracting orbit from Orbit File:  orbit/S1A_OPER_AUX_POEORB_OPOD_20220201T121555_V20220111T225942_20220113T005942.EOF
Updating burst number from 1 to 1
Updating burst number from 2 to 2
Updating burst number from 3 to 3
Updating burst number from 4 to 4
Updating burst number from 5 to 5
Updating burst number from 6 to 6
Updating burst number from 7 to 7
Updating burst number from 8 to 8
Updating burst number from 9 to 9
Input XML files:  ['/vsizip/S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.zip/S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/annotation/s1a-iw2-slc-vh-20220117t231322-20220117t231347-041507-04ef9f-002.xml']
Input TIFF files:  ['/vsizip/S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.zip/S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/measurement/s1a-iw2-slc-vh-20220117t231322-20220117t231347-041507-04ef9f-002.tiff']
Manifest files:  ['/vsizip/S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.zip/S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/manifest.safe']
MANS:  S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.zip S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.SAFE/manifest.safe
Setting IPF version to :  003.40
Extracting orbit from Orbit File:  orbit/S1A_OPER_AUX_POEORB_OPOD_20220206T081641_V20220116T225942_20220118T005942.EOF
Updating burst number from 1 to 1
Updating burst number from 2 to 2
Updating burst number from 3 to 3
Updating burst number from 4 to 4
Updating burst number from 5 to 5
Updating burst number from 6 to 6
Updating burst number from 7 to 7
Updating burst number from 8 to 8
Updating burst number from 9 to 9
2023-10-19 12:20:31,272 - isce.topsinsar.runPreprocessor - INFO - 
####################################################################################################
    runPreprocessor
----------------------------------------------------------------------------------------------------
common.Input list of swaths to process:  = [2]
reference.burstLength_2 = 1506
reference.burstWidth_2 = 25119
reference.numberOfBursts_2 = 9
reference.sensor.ascendingnodetime = 2022-01-12 22:23:59.565969
reference.sensor.family = topsswathslc
reference.sensor.folder = None
reference.sensor.imagingmode = TOPS
reference.sensor.mission = S1A
reference.sensor.name = topsswathslc_name
reference.sensor.numberofbursts = 9
reference.sensor.processingfacility = Airbus Defence and Space-Toulouse, France
reference.sensor.processingsoftwareversion = 003.40
reference.sensor.processingsystem = Sentinel-1 IPF
reference.sensor.spacecraftname = Sentinel-1
secondary.burstLength_2 = 1509
secondary.burstWidth_2 = 25432
secondary.numberOfBursts_2 = 9
secondary.sensor.ascendingnodetime = 2022-01-17 22:32:12.903609
secondary.sensor.family = topsswathslc
secondary.sensor.folder = None
secondary.sensor.imagingmode = TOPS
secondary.sensor.mission = S1A
secondary.sensor.name = topsswathslc_name
secondary.sensor.numberofbursts = 9
secondary.sensor.processingfacility = Airbus Defence and Space-Toulouse, France
secondary.sensor.processingsoftwareversion = 003.40
secondary.sensor.processingsystem = Sentinel-1 IPF
secondary.sensor.spacecraftname = Sentinel-1
####################################################################################################
Traceback (most recent call last):
  File "/home/maqingbo/tools/src/isce2/applications/topsApp.py", line 1077, in <module>
    insar.run()
  File "/home/maqingbo/anaconda3/envs/isce2/lib/python3.8/site-packages/isce/components/iscesys/Component/Application.py", line 144, in run
    exitStatus = self.main()
  File "/home/maqingbo/tools/src/isce2/applications/topsApp.py", line 991, in main
    self.runComputeBaseline()
  File "/home/maqingbo/anaconda3/envs/isce2/lib/python3.8/site-packages/isce/components/isceobj/TopsProc/Factories.py", line 40, in __call__
    return self.method(self.other, *args, **kwargs)
  File "/home/maqingbo/anaconda3/envs/isce2/lib/python3.8/site-packages/isce/components/isceobj/TopsProc/runComputeBaseline.py", line 36, in runComputeBaseline
    burstOffset, minBurst, maxBurst = reference.getCommonBurstLimits(secondary)
  File "/home/maqingbo/anaconda3/envs/isce2/lib/python3.8/site-packages/isce/components/isceobj/Sensor/TOPS/TOPSSwathSLCProduct.py", line 266, in getCommonBurstLimits
    burstoffset = self.getBurstOffset(sFrame)
  File "/home/maqingbo/anaconda3/envs/isce2/lib/python3.8/site-packages/isce/components/isceobj/Sensor/TOPS/TOPSSwathSLCProduct.py", line 258, in getBurstOffset
    raise  Exception('Could not determine a suitable burst offset')
Exception: Could not determine a suitable burst offset

``` 

INPUT XML FILE:
```
topsApp.xml:
<?xml version="1.0" encoding="UTF-8"?>
<topsApp>
  <component name="topsinsar">
    <property name="Sensor name">SENTINEL1</property>
    <property name="filter strength">0.4</property>
    <property name="swaths">[2]</property>
    <property name="do ESD">True</property>
    <component name="reference">
        <catalog>reference.xml</catalog>
    </component>
    <component name="secondary">
        <catalog>secondary.xml</catalog>
    </component>
  </component>
</topsApp>

reference.xml:
<?xml version="1.0" encoding="UTF-8"?>
<component name="reference">
  <property name="safe">
    <value>S1A_IW_SLC__1SDV_20220112T230511_20220112T230538_041434_04ED3C_6FC4.zip</value>
  </property>
  <property name="orbit directory">
      <value>orbit</value>
  </property>
  <property name="polarization">'vh'</property>
  <property name="output directory">
    <value>output/20220112</value>
  </property>
</component>

secondary xml:
<?xml version="1.0" encoding="UTF-8"?>
<component name="secondary">
  <property name="safe">
    <value>S1A_IW_SLC__1SDV_20220117T231320_20220117T231347_041507_04EF9F_781F.zip</value>
  </property>
  <property name="orbit directory">
      <value>orbit</value>
  </property>
  <property name="polarization">'vh'</property>
  <property name="output directory">
    <value>output/20220117</value>
  </property>
</component>
```

**Comment by rtburns-jpl** [comment]
I was able to download these SLC files and get the same error as you, but I think that's expected. I think the SLCs you picked were simply too far apart to do InSAR on.

Here's what the overlap looks like on ASF Vertex:
<img width="529" alt="image" src="https://github.com/isce-framework/isce2/assets/47790121/9888dfdd-078d-498a-a6fb-ea71412ccd13">

They're hardly overlapping because they're not from the same frame. These SLCs were taken 5 days apart but Sentinel-1 has a 12-day repeat cycle.

I'd suggest using ASF Vertex's Baseline Tool to find pairs which are suitable for InSAR.
