### ISSUE TITLE
StripmapApp interferogram geocode error

### ISSUE THREAD

**Issue by jsidhu45** [isce-framework/isce2#790]
Hi, 

I am new to SAR processing using ISCE2. I was following the InSAR pair processing with stripmapApp notebook for learing the processing workflow. I was able to exceute almost all the commands, but met with an error on last step of interferogram geocode. 

stripmapApp.py stripmapApp.xml --start=geocode  --end=geocode

Using default ISCE Path: /home/jovyan/.local/envs/isce2/lib/python3.12/site-packages/isce
2023-11-19 05:51:29,687 - isce.insar - INFO - ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION = 
ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION = 
2023-11-19 05:51:29,690 - root - INFO - reference sensor not provided explicitly, using common sensor
2023-11-19 05:51:29,716 - root - INFO - secondary sensor not provided explicitly, using common sensor
do_unwrap  True
Step processing
Running step geocode
2023-11-19 05:51:29,936 - isce.topsinsar.runGeocode - INFO - Geocoding Image
Number of products to geocode:  6
Traceback (most recent call last):
  File "/home/jovyan/.local/envs/isce2/bin/stripmapApp.py", line 1002, in <module>
    status = insar.run()
             ^^^^^^^^^^^
  File "/home/jovyan/.local/envs/isce2/lib/python3.12/site-packages/isce/components/iscesys/Component/Application.py", line 142, in run
    exitStatus = self._processSteps()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.local/envs/isce2/lib/python3.12/site-packages/isce/components/iscesys/Component/Application.py", line 405, in _processSteps
    result = func(*pargs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.local/envs/isce2/lib/python3.12/site-packages/isce/components/isceobj/StripmapProc/Factories.py", line 46, in __call__
    return self.method(self.other, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.local/envs/isce2/lib/python3.12/site-packages/isce/components/isceobj/StripmapProc/runGeocode.py", line 55, in runGeocode
    burst = self._insar.loadProduct( self._insar.referenceSlcCropProduct)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.local/envs/isce2/lib/python3.12/site-packages/isce/components/isceobj/StripmapProc/StripmapProc.py", line 602, in loadProduct
    obj = pm.loadProduct(xmlname)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.local/envs/isce2/lib/python3.12/site-packages/isce/components/iscesys/Component/ProductManager.py", line 25, in loadProduct
    self.load(filename)
  File "/home/jovyan/.local/envs/isce2/lib/python3.12/site-packages/isce/components/iscesys/Component/Configurable.py", line 1407, in load
    tmpProp, tmpFact, tmpMisc = FP.parse(filename)
                                ^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.local/envs/isce2/lib/python3.12/site-packages/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse
    root = ET.parse(filename)

**Comment by EJFielding** [comment]
You have to complete all the steps before the geocoding before running the `geocode` step. It looks like it is not finding one of the files that should have been created by a previous step.
