### ISSUE TITLE
stackSentinel.py IndexError: list index out of range

### ISSUE THREAD

**Issue by mirzawaqar** [isce-framework/isce2#813]
I am getting IndexError: list Index out of range error. Any issue where I am wrong?

**stackSentinel.py -s SLC/ -d DEM/demLat_N38_N39_Lon_E127_E128.dem.wgs84 -b '38.3 38.5 127.1 127.3' -a aux/ -o orbits/ -C NESD -W slc**

Number of SAFE files found: 177
2024-01-23 16:15:01,785 - matplotlib - DEBUG - matplotlib data path: /home/contec/miniconda3/envs/isce2/lib/python3.8/site-packages/matplotlib/mpl-data
2024-01-23 16:15:01,790 - matplotlib - DEBUG - CONFIGDIR=/home/contec/.config/matplotlib
2024-01-23 16:15:01,791 - matplotlib - DEBUG - interactive is False
2024-01-23 16:15:01,791 - matplotlib - DEBUG - platform is linux
*****************************************
20191211
orbit was not found in the /HHD3/Research/RD002_Land_Deformation_Assessment/North_Korea/Hwanggang_Dam/asc/data/orbits
downloading precise or restituted orbits ...
Traceback (most recent call last):
  File "/home/contec/Softwares/ISCE_2.3/isce2-2.3.2/contrib/stack/topsStack/stackSentinel.py", line 736, in <module>
    main()
  File "/home/contec/Softwares/ISCE_2.3/isce2-2.3.2/contrib/stack/topsStack/stackSentinel.py", line 700, in main
    acquisitionDates, stackMasterDate, slaveDates, safe_dict, updateStack = checkCurrentStatus(inps)
  File "/home/contec/Softwares/ISCE_2.3/isce2-2.3.2/contrib/stack/topsStack/stackSentinel.py", line 577, in checkCurrentStatus
    acquisitionDates, stackMasterDate, slaveDates, safe_dict = get_dates(inps)
  File "/home/contec/Softwares/ISCE_2.3/isce2-2.3.2/contrib/stack/topsStack/stackSentinel.py", line 243, in get_dates
    safeObj.get_orbit(inps.orbit_dirname, inps.work_dir)
  File "/home/contec/Softwares/ISCE_2.3/isce2-2.3.2/contrib/stack/topsStack/Stack.py", line 909, in get_orbit
    orbitFile = glob.glob(os.path.join(restitutedOrbitDir,'*.EOF'))[0]
IndexError: list index out of range

**Comment by yuyanru0304** [comment]
the same issue, do you solve it?
