### ISSUE TITLE
Troubles with memMap Saving from a RawIQImage

### ISSUE THREAD

**Issue by cg0978** [isce-framework/isce2#817]
I am trying to save a raw image of an iq.xml after performing a stripmapApp file but I continue to receive an error below:

````
Traceback (most recent call last):
File "iq_raw_image_save.py", line 12, in <module>
tmp = img.memMap(mode='w+')
File "ISCE_PATH/components/isceobj/Image/Image.py", line 326, in memMap
immap = np.memmap(self.filename, self.toNumpyDataType(), mode,
File "ISCE_PATH/components/isceobj/Image/Image.py", line 256, in toNumpyDataType
return TO_NUMPY[self.dataType.upper()]

KeyError: 'CIQBYTE'
````
 
I have looked into the error but cannot find any solution to avoid the KeyError. My python script is:

````
import isce
import isceobj
import numpy as np
from numpy.lib.format import open_memmap
from isceobj.Image import createRawIQImage

img = isceobj.createRawIQImage()
img.load('./RAW_DIRECTORY/RAWImageiq.xml')

tmp = img.memMap(mode='w+')

img = open_memmap('RAWIQ_OUTPUT.rawIQ.npy', mode='w+', dtype=tmp.dtype, shape=tmp.shape)

img = tmp   

np.save('RAWIQ_OUTPUT.rawIQ.npy', img)
````

Any guidance would be greatly appreciated :)

**Comment by cg0978** [comment]
I found the issue that there is no 'CIQBYTE' within TO_NUMPY.
