### ISSUE TITLE
Bug when using unwrap2stage in topsApp.py

### ISSUE THREAD

**Issue by lincoln-olayta** [isce-framework/isce2#826]
Hi, 

I'm doing topsApp.py processing for certain interferogram pair, and wanted to explore the option of using unw2stage. 
Here's the setting to apply unwrap2stage in topsApp.xml

`    <property name="unwrapper name">snaphu_mcf</property>
    <property name="do unwrap">True</property>
    
    <property name="do unwrap2stage">True</property>
    <property name="unwrapper 2 stage name">MCF</property> `

Most of the steps are working, until the unwrap2stage:

Here's the error code:

` /Users/irides_olayta/opt/anaconda3/envs/isce2/lib/python3.12/site-packages/pulp/pulp.py:1316: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")
Traceback (most recent call last):
  File "/Users/irides_olayta/opt/anaconda3/envs/isce2/packages/isce/applications/topsApp.py", line 1077, in <module>
    insar.run()
  File "/Users/irides_olayta/opt/anaconda3/envs/isce2/lib/python3.12/site-packages/isce/components/iscesys/Component/Application.py", line 142, in run
    exitStatus = self._processSteps()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/irides_olayta/opt/anaconda3/envs/isce2/lib/python3.12/site-packages/isce/components/iscesys/Component/Application.py", line 405, in _processSteps
    result = func(*pargs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/irides_olayta/opt/anaconda3/envs/isce2/lib/python3.12/site-packages/isce/components/isceobj/TopsProc/Factories.py", line 40, in __call__
    return self.method(self.other, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/irides_olayta/opt/anaconda3/envs/isce2/lib/python3.12/site-packages/isce/components/isceobj/TopsProc/runUnwrap2Stage.py", line 38, in runUnwrap2Stage
    unw.unwrapComponents()
  File "/Users/irides_olayta/opt/anaconda3/envs/isce2/lib/python3.12/site-packages/isce/components/contrib/UnwrapComp/unwrapComponents.py", line 109, in unwrapComponents
    self.__run__()
  File "/Users/irides_olayta/opt/anaconda3/envs/isce2/lib/python3.12/site-packages/isce/components/contrib/UnwrapComp/unwrapComponents.py", line 250, in __run__
    phaseunwrap = PhaseUnwrap(x=x, y=y, phase=self.inpAcc[y,x], compNum=compnum, redArcs=redarcsTypes[self.redArcs])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/irides_olayta/opt/anaconda3/envs/isce2/lib/python3.12/site-packages/isce/components/contrib/UnwrapComp/phaseUnwrap.py", line 368, in __init__
    self.__adjMat           = self.__getAdjMat(delauneyTri.vertices)
                                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Delaunay' object has no attribute 'vertices' `

I tried downgrading the version of PuLP (from 2.8.0 to 2.7.0) but still does not resolve the issue. Just thought you should know.

I'm using ISCE 2.6.3 installed on Mac M1 arm64, with Pulp and RelaxIV compiled together using cmake. (following lijun99 guide) 
Running on Python 3.12.

**Comment by rtburns-jpl** [comment]
Thanks for this, it looks like this is the issue:

```
    self.__adjMat           = self.__getAdjMat(delauneyTri.vertices)
                                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Delaunay' object has no attribute 'vertices' 
```

I think Delaunay.vertices has been deprecated in scipy and was finally removed in scipy 1.11.

According to scipy documentation, it has been replaced with simplices. Does changing the above line from `.vertices` to `.simplices` fix this issue for you? I'll push that fix if it is sufficient.
