### ISSUE TITLE
topsApp.py error

### ISSUE THREAD

**Issue by bjmarfito** [isce-framework/isce2#849]
I encountered this error when running topsApp.py in a new computer.

```
Using default ISCE Path: /home/bryanjim001/.conda/envs/isce2expe/lib/python3.12/site-packages/isce
Traceback (most recent call last):
  File "/home/bryanjim001/.conda/envs/isce2expe/lib/python3.12/site-packages/isce2/applications/topsApp.py", line 46, in <module>
    from isceobj import TopsProc
  File "/home/bryanjim001/.conda/envs/isce2expe/lib/python3.12/site-packages/isce/components/isceobj/TopsProc/__init__.py", line 7, in <module>
    from .Factories import *
  File "/home/bryanjim001/.conda/envs/isce2expe/lib/python3.12/site-packages/isce/components/isceobj/TopsProc/Factories.py", line 90, in <module>
    createIon = _factory("runIon")
                ^^^^^^^^^^^^^^^^^^
  File "/home/bryanjim001/.conda/envs/isce2expe/lib/python3.12/site-packages/isce/components/isceobj/TopsProc/Factories.py", line 15, in _factory
    module = __import__(
             ^^^^^^^^^^^
  File "/home/bryanjim001/.conda/envs/isce2expe/lib/python3.12/site-packages/isce/components/isceobj/TopsProc/runIon.py", line 17, in <module>
    from isceobj.Alos2Proc.runIonFilt import reformatMaskedAreas
  File "/home/bryanjim001/.conda/envs/isce2expe/lib/python3.12/site-packages/isce/components/isceobj/Alos2Proc/__init__.py", line 7, in <module>
    from .Factories import *
  File "/home/bryanjim001/.conda/envs/isce2expe/lib/python3.12/site-packages/isce/components/isceobj/Alos2Proc/Factories.py", line 88, in <module>
    createRdrDemOffset = _factory("runRdrDemOffset")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bryanjim001/.conda/envs/isce2expe/lib/python3.12/site-packages/isce/components/isceobj/Alos2Proc/Factories.py", line 15, in _factory
    module = __import__(
             ^^^^^^^^^^^
  File "/home/bryanjim001/.conda/envs/isce2expe/lib/python3.12/site-packages/isce/components/isceobj/Alos2Proc/runRdrDemOffset.py", line 16, in <module>
    from contrib.alos2proc_f.alos2proc_f import fitoff
ImportError: /home/bryanjim001/.conda/envs/isce2expe/lib/python3.12/site-packages/isce/components/contrib/alos2proc_f/alos2proc_f.so: undefined symbol: PyCode_NewWithPosOnlyArgs
```

**Comment by bjmarfito** [comment]
I downgraded to Python 3.11 and it worked. Probably a Python 3.12 issue

**Comment by bjmarfito** [comment]
My system is compiling the code using Python 3.11 instead of Python 3.12. Fixed it now.

Closing this issue.
