### ISSUE TITLE
runESD error

### ISSUE THREAD

**Issue by srcgps** [isce-framework/isce2#856]
Hello,

I am using topsapp.py to process sentinel data. I received the error shown below. Any advice would be appreciated.

GDAL open (R): ESD/freq_IW3_08.bin.vrt
API open (WR): ESD/freq_IW3_08.5alks_15rlks.bin
GDAL close: ESD/freq_IW3_08.bin.vrt
API close:  ESD/freq_IW3_08.5alks_15rlks.bin
API open (R): ESD/freq_IW3_08.5alks_15rlks.bin
API close:  ESD/freq_IW3_08.5alks_15rlks.bin
Writing geotrans to VRT for ESD/freq_IW3_08.5alks_15rlks.bin
Output:  ESD/freq_IW3_08.5alks_15rlks.bin
Traceback (most recent call last):
  File "/home/srcgps/miniconda3/envs/isce2/bin/topsApp.py", line 1077, in <module>
    insar.run()
  File "/home/srcgps/miniconda3/envs/isce2/lib/python3.12/site-packages/isce/components/iscesys/Component/Application.py", line 144, in run
    exitStatus = self.main()
                 ^^^^^^^^^^^
  File "/home/srcgps/miniconda3/envs/isce2/bin/topsApp.py", line 1017, in main
    self.runESD()
  File "/home/srcgps/miniconda3/envs/isce2/lib/python3.12/site-packages/isce/components/isceobj/TopsProc/Factories.py", line 40, in __call__
    return self.method(self.other, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/srcgps/miniconda3/envs/isce2/lib/python3.12/site-packages/isce/components/isceobj/TopsProc/runESD.py", line 117, in runESD
    raise Exception('Coherence threshold too strict. No points left for reliable ESD estimate')
Exception: Coherence threshold too strict. No points left for reliable ESD estimate

Thank you.

**Comment by itingwanggeo** [comment]
Hello, 

I encounter the same issue. Have you solve the problem?

Thanks.
