### ISSUE TITLE
Issues when processing TerraSAR-X images with stripmapApp

### ISSUE THREAD

**Issue by david-ncu2019** [isce-framework/isce2#866]
Dear everyone,

I am encountering some issues that have been quite time-consuming, and despite re-running the entire process, the problems still persist. I would appreciate it if ISCE developers and users could take a moment to review this and offer some advice.

If someone knows the directions, please give me some tips on how to deal with the errors.

Below, I will list the errors I encountered at each step.

#### run_05_refineSecondaryTiming
Traceback (most recent call last):
  File `"/home/davidncu/tools/src/isce2/contrib/stack/stripmapStack/stripmapWrapper.py"`, line 155, in <module>
    main(args.start,args.end)
  File `"/home/davidncu/tools/src/isce2/contrib/stack/stripmapStack/stripmapWrapper.py"`, line 146, in main
    cfgParser.runCmd()
  File `"/home/davidncu/tools/src/isce2/contrib/stack/stripmapStack/stripmapWrapper.py"`, line 51, in runCmd
    func_modules.main(self.funcParams[section])
  File `"/home/davidncu/tools/src/isce2/contrib/stack/stripmapStack/refineSecondaryTiming.py"`, line 221, in main
    shifts, cull = fitOffsets(field,azazOrder=inps.azazorder,
  File `"/home/davidncu/tools/src/isce2/contrib/stack/stripmapStack/refineSecondaryTiming.py"`, line 157, in fitOffsets
    aa, dummy = field.getFitPolynomials(azimuthOrder=azazOrder, rangeOrder=azrgOrder, usenumpy=True)
  File `"/home/davidncu/miniconda3/envs/isce_project/lib/python3.8/site-packages/isce/components/isceobj/Location/Offset.py"`, line 413, in getFitPolynomials
    azmin = np.min(inArr[:,2])
`IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed`

Before that, there is **no error** shown in the log files for steps 1 to 4

#### run_06_invertMisreg
(these errors may be due the error from step 5)
**Missing keys in shelve file**: /media/davidncu/VTRUONG_1TB/JupyterLab_Workspace/TSX_Processing/Run008/ISCE_output/refineSecondaryTiming/pairs/20230410_20230421

Then there is **no error* shown in the step 7, 8, and 9.

#### smallbaselineApp.py <template> --dostep load_data
But then, when I run `load_data` from MintPy, I encounter another issue:

`searching geometry files info`
input data files:
height          : /media/davidncu/VTRUONG_1TB/JupyterLab_Workspace/TSX_Processing/Run008/ISCE_output/geom_reference/hgt.rdr
latitude        : /media/davidncu/VTRUONG_1TB/JupyterLab_Workspace/TSX_Processing/Run008/ISCE_output/geom_reference/lat.rdr
longitude       : /media/davidncu/VTRUONG_1TB/JupyterLab_Workspace/TSX_Processing/Run008/ISCE_output/geom_reference/lon.rdr
incidenceAngle  : /media/davidncu/VTRUONG_1TB/JupyterLab_Workspace/TSX_Processing/Run008/ISCE_output/geom_reference/los.rdr
azimuthAngle    : /media/davidncu/VTRUONG_1TB/JupyterLab_Workspace/TSX_Processing/Run008/ISCE_output/geom_reference/los.rdr
waterMask       : /media/davidncu/VTRUONG_1TB/JupyterLab_Workspace/TSX_Processing/Run008/ISCE_output/geom_reference/waterMask.rdr

`create HDF5 file` /media/davidncu/VTRUONG_1TB/JupyterLab_Workspace/TSX_Processing/Run008/MintPy_v1/inputs/geometryRadar.h5 with w mode
create dataset /height             of <class 'numpy.float32'>   in size of (2945, 1672) with compression = lzf
create dataset /latitude           of <class 'numpy.float32'>   in size of (2945, 1672) with compression = lzf
create dataset /longitude          of <class 'numpy.float32'>   in size of (2945, 1672) with compression = lzf
create dataset /incidenceAngle     of <class 'numpy.float32'>   in size of (2945, 1672) with compression = lzf
create dataset /azimuthAngle       of <class 'numpy.float32'>   in size of (2945, 1672) with compression = lzf
create dataset /waterMask          of <class 'numpy.bool_'>     in size of (2945, 1672) with compression = lzf
prepare slantRangeDistance ...
**Traceback (most recent call last):
  File "/home/davidncu/miniconda3/envs/isce_project/bin/smallbaselineApp.py", line 8, in <module>
    sys.exit(main())
  File "/home/davidncu/miniconda3/envs/isce_project/lib/python3.8/site-packages/mintpy/cli/smallbaselineApp.py", line 209, in main
    run_smallbaselineApp(inps)
  File "/home/davidncu/miniconda3/envs/isce_project/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 1155, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/home/davidncu/miniconda3/envs/isce_project/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 908, in run
    self.run_load_data(sname)
  File "/home/davidncu/miniconda3/envs/isce_project/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 176, in run_load_data
    mintpy.cli.load_data.main(iargs)
  File "/home/davidncu/miniconda3/envs/isce_project/lib/python3.8/site-packages/mintpy/cli/load_data.py", line 123, in main
    load_data(inps)
  File "/home/davidncu/miniconda3/envs/isce_project/lib/python3.8/site-packages/mintpy/load_data.py", line 849, in load_data
    geom_radar_obj.write2hdf5(
  File "/home/davidncu/miniconda3/envs/isce_project/lib/python3.8/site-packages/mintpy/objects/stackDict.py", line 761, in write2hdf5
    data = self.get_slant_range_distance(box=box, xstep=xstep, ystep=ystep)
  File "/home/davidncu/miniconda3/envs/isce_project/lib/python3.8/site-packages/mintpy/objects/stackDict.py", line 504, in get_slant_range_distance
    data = ut.range_distance(self.extraMetadata,
  File "/home/davidncu/miniconda3/envs/isce_project/lib/python3.8/site-packages/mintpy/utils/utils0.py", line 78, in range_distance
    **range_n, dR = float(atr['STARTING_RANGE']), float(atr['RANGE_PIXEL_SIZE'])**
`KeyError: 'STARTING_RANGE'`**

**Comment by david-ncu2019** [comment]
I myself found the solutions. However, they are just temporary approaches to make the scripts implement normally, the detailed technical issues will not be mentioned here.

### **run_05_refineSecondaryTiming**

To prevent the error `IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed`, I run this script as a single process, instead of running all script automatically.
Then, after the program finishes, I check the `misreg.dir` file in folder ./refineSecondaryTiming/pairs/`ref`_`sec`/, if the file contains 4 components 'raw_field', 'cull_field', 'azpoly', and 'rgpoly', my file is okay.
Otherwise, I need to re-run `refineSecondaryTiming.py` manually, input the parameters similar to contents of `config_refineSecondaryTiming`, but **change the SNR threshold to a lower value (default value is 5.0)**
(I did all the steps above using a Python program to loop through file and process)

When there are no more error file from **run_05_refineSecondaryTiming**, I can implement `run_06_invertMisreg` without any errors or warnings.

### **KeyError: 'STARTING_RANGE'**
To prevent the **KeyError: 'STARTING_RANGE'**, I need to check the output files in ./geom_reference (using `view.py` to plot the file). If the files contain null-value, I have to re-run **run_02_reference** manually.
First, I run `topo.py`, the input parameters are shown in `config_reference` . Regarding how to input them, just type `topo.py --help` to see the instruction.
Then, I run `createWaterMask` manually as well.

Afterwards, I come back the folder ./geom_reference to check the output files, now they are all okay.

Subsequently, you continue to run other scripts (and remember to run script run_05_refineSecondaryTiming as a single step to control the output)
