### ISSUE TITLE
Problem with run_05_overlap_geo2rdr

### ISSUE THREAD

**Issue by fpucci** [isce-framework/isce2#910]
We have a problem on some S1 data when running stackSentinel application.
Full stack trace is:
`
1:23:49;INFO;b"['--secondary', '/home/mambauser/data/processes/S1_ASC_2019_2024_1/work_coreg_Sentinel1/secondarys/20230710', '--reference', '/home/mambauser/data/processes/S1_ASC_2019_2024_1/work_coreg_Sentinel1/reference', '--geom_referenceDir', '/home/mambauser/data/processes/S1_ASC_2019_2024_1/work_coreg_Sentinel1/geom_reference', '--coregSLCdir', '/home/mambauser/data/processes/S1_ASC_2019_2024_1/work_coreg_Sentinel1/coreg_secondarys/20230710', '--overlap']\n"
03-12-2024 11:23:49;INFO;b'CPU mode\n'
03-12-2024 11:23:49;INFO;b'Traceback (most recent call last):\n'
03-12-2024 11:23:49;INFO;b'  File "/opt/conda/share/isce2/topsStack/SentinelWrapper.py", line 251, in <module>\n'
03-12-2024 11:23:49;INFO;b'    main(args.start,args.end)\n'
03-12-2024 11:23:49;INFO;b'  File "/opt/conda/share/isce2/topsStack/SentinelWrapper.py", line 242, in main\n'
03-12-2024 11:23:49;INFO;b'    cfgParser.runCmd()\n'
03-12-2024 11:23:49;INFO;b'  File "/opt/conda/share/isce2/topsStack/SentinelWrapper.py", line 54, in runCmd\n'
03-12-2024 11:23:49;INFO;b'    func_modules.main(self.funcParams[section])\n'
03-12-2024 11:23:49;INFO;b'  File "/opt/conda/share/isce2/topsStack/geo2rdr.py", line 235, in main\n'
03-12-2024 11:23:49;INFO;b"    secondary = ut.loadProduct(os.path.join(inps.secondary, 'IW{0}.xml'.format(swath)))\n"
03-12-2024 11:23:49;INFO;b'  File "/opt/conda/share/isce2/topsStack/s1a_isce_utils.py", line 26, in loadProduct\n'
03-12-2024 11:23:49;INFO;b'    obj = pm.loadProduct(xmlname)\n'
03-12-2024 11:23:49;INFO;b'  File "/opt/conda/lib/python3.9/site-packages/isce/components/iscesys/Component/ProductManager.py", line 25, in loadProduct\n'
03-12-2024 11:23:49;INFO;b'    self.load(filename)\n'
03-12-2024 11:23:49;INFO;b'  File "/opt/conda/lib/python3.9/site-packages/isce/components/iscesys/Component/Configurable.py", line 1407, in load\n'
03-12-2024 11:23:49;INFO;b'    tmpProp, tmpFact, tmpMisc = FP.parse(filename)\n'
03-12-2024 11:23:49;INFO;b'  File "/opt/conda/lib/python3.9/site-packages/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse\n'
03-12-2024 11:23:49;INFO;b'    root = ET.parse(filename)\n'
03-12-2024 11:23:49;INFO;b'  File "/opt/conda/lib/python3.9/xml/etree/ElementTree.py", line 1222, in parse\n'
03-12-2024 11:23:49;INFO;b'    tree.parse(source, parser)\n'
03-12-2024 11:23:49;INFO;b'  File "/opt/conda/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse\n'
03-12-2024 11:23:49;INFO;b'    source = open(source, "rb")\n'
03-12-2024 11:23:49;INFO;b"FileNotFoundError: [Errno 2] No such file or directory: '/home/mambauser/data/processes/S1_ASC_2019_2024_1/work_coreg_Sentinel1/secondarys/20230710/IW3.xml'\n"`

Thanks in advance for your help.

**Comment by RSthinker** [comment]
I have the same problem, and until step 05, the only possiblem problem i found is the dem range and clip area unmatched later i will retry to make clip area range is within dem range.
