### ISSUE TITLE
Error Using StripmapApp.py

### ISSUE THREAD

**Issue by arnavgarg233** [isce-framework/isce2#912]
When I try to use StripmapApp.py on SENTINEL-1 data, the object, sensor, is missing a variable and isn't initialized properly. The code block above is the error logs that I receive when I run StripmapApp.py, and the bottom code block is located in runPreprocessor.py where sensor is defined. I wanted to know where self.reference is defined, since that seems to be how sensor is defined based on the second code block. Alternatively, if anyone knows how to fix the issue I would really appreciate it.
```
`(isce2)arnav@GalaxyBook:~/tools/src/isce2$ stripmapApp.py /home/arnav/tools/src/isce2/applications/referencefiles/reference_SENTINEL1.xml

Using default ISCE Path: /home/arnav/miniforge3/envs/isce2/lib/python3.13/site-packages/isce
2024-12-15 11:04:50,621 - isce.insar - INFO - ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION = 
ISCE VERSION = 2.6.3, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20230418, CURRENT_SVN_REVISION = 
do_unwrap  True
running unwrapping grass

Insar Application:
Implements InSAR processing flow for a pair of scenes from
sensor raw data to geocoded, flattened interferograms.

The currently supported sensors are:  ['ALOS', 'ALOS2', 'ALOS_SLC', 'COSMO_SKYMED', 'COSMO_SKYMED_SLC', 'ENVISAT', 'ENVISAT_SLC', 'ERS', 'ERS_ENVISAT', 'ERS_ENVISAT_SLC', 'ERS_SLC', 'ICEYE_SLC', 'KOMPSAT5', 'LUTAN1', 'RADARSAT1', 'RADARSAT2', 'RISAT1', 'RISAT1_SLC', 'ROI_PAC', 'SAOCOM_SLC', 'SENTINEL1', 'SICD_RGZERO', 'TERRASARX', 'UAVSAR_HDF5_SLC', 'UAVSAR_POLSAR', 'UAVSAR_RPI', 'UAVSAR_STACK']
Traceback (most recent call last):
  File "/home/arnav/miniforge3/envs/isce2/bin/stripmapApp.py", line 1002, in <module>
    status = insar.run()
  File "/home/arnav/miniforge3/envs/isce2/lib/python3.13/site-packages/isce/components/iscesys/Component/Application.py", line 144, in run
    exitStatus = self.main()
  File "/home/arnav/miniforge3/envs/isce2/bin/stripmapApp.py", line 956, in main
    super().main()
    ~~~~~~~~~~~~^^
  File "/home/arnav/miniforge3/envs/isce2/bin/stripmapApp.py", line 836, in main
    self.runPreprocessor()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/home/arnav/miniforge3/envs/isce2/lib/python3.13/site-packages/isce/components/isceobj/StripmapProc/Factories.py", line 46, in __call__
    return self.method(self.other, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arnav/miniforge3/envs/isce2/lib/python3.13/site-packages/isce/components/isceobj/StripmapProc/runPreprocessor.py", line 49, in runPreprocessor
    dirname = sensor.output
              ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute output`
```
```
 sensor = copy.deepcopy(self.reference)
    dirname = sensor.output

    if self.referenceSensorName is None:
        self.referenceSensorName = self.sensorName

**Comment by Sci123-lab** [comment]
I suppose you must have solved the problem by now. Your Sentinel-1 dataset might be in IW mode, which you need to process using topsApp.py
